
SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for `201905_carrierstate`
-- ----------------------------
DROP TABLE IF EXISTS `201905_carrierstate`;
CREATE TABLE `201905_carrierstate` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `carrier_id_name` varchar(30) DEFAULT NULL,
  `carrier_ipaddress` varchar(30) DEFAULT NULL,
  `bill_duration` int(11) DEFAULT '0',
  `carrier_duration` int(11) DEFAULT '0',
  `carrier_currency_id` int(11) DEFAULT '0',
  `carrier_cost` double(12,6) DEFAULT '0.000000',
  `totalcalls` int(11) DEFAULT '0',
  `answeredcalls` int(11) DEFAULT '0',
  `carrier_prefix` varchar(20) DEFAULT NULL,
  `carrier_prefix_name` varchar(50) DEFAULT NULL,
  `call_date` date DEFAULT NULL,
  `calltime_h` varchar(5) DEFAULT '0',
  `calltime_m` varchar(5) DEFAULT '0',
  `pdd` int(11) DEFAULT '0',
  `fscause` varchar(150) DEFAULT NULL,
  `Q850CODE` int(11) DEFAULT NULL,
  `SIPCODE` int(11) DEFAULT NULL,
  `carrier_name` varchar(150) DEFAULT NULL,
  `cdr_type` varchar(5) DEFAULT 'OUT',
  PRIMARY KEY (`id`),
  UNIQUE KEY `carrier_id_name_key` (`carrier_id_name`,`call_date`,`calltime_h`,`calltime_m`,`Q850CODE`,`SIPCODE`,`fscause`,`carrier_ipaddress`,`cdr_type`) USING BTREE,
  KEY `call_date` (`call_date`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- ----------------------------
-- Records of 201905_carrierstate
-- ----------------------------

-- ----------------------------
-- Table structure for `201905_cdr`
-- ----------------------------
DROP TABLE IF EXISTS `201905_cdr`;
CREATE TABLE `201905_cdr` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `common_uuid` varchar(300) DEFAULT NULL,
  `carrier_dialplan_id` varchar(30) DEFAULT NULL,
  `caller_callid` varchar(150) DEFAULT NULL,
  `callee_callid` varchar(150) DEFAULT NULL,
  `uuid` varchar(150) DEFAULT NULL,
  `sip_from_user` varchar(150) DEFAULT NULL,
  `sip_from_uri` varchar(150) DEFAULT NULL,
  `sip_from_host` varchar(150) DEFAULT NULL,
  `channel_name` varchar(150) DEFAULT NULL,
  `sip_call_id` varchar(150) DEFAULT NULL,
  `ep_codec_string` varchar(300) DEFAULT NULL,
  `sip_network_ip` varchar(150) DEFAULT NULL,
  `dialstatus` varchar(30) DEFAULT NULL,
  `sip_received_ip` varchar(30) DEFAULT NULL,
  `sip_received_port` varchar(7) DEFAULT NULL,
  `sip_via_protocol` varchar(30) DEFAULT NULL,
  `sip_from_user_stripped` varchar(150) DEFAULT NULL,
  `sip_from_display` varchar(150) DEFAULT NULL,
  `sip_full_from` varchar(150) DEFAULT NULL,
  `sip_to_display` varchar(30) DEFAULT NULL,
  `sip_full_to` varchar(150) DEFAULT NULL,
  `sip_req_user` varchar(150) DEFAULT NULL,
  `sip_req_uri` varchar(150) DEFAULT NULL,
  `sip_to_user` varchar(150) DEFAULT NULL,
  `sip_to_uri` varchar(150) DEFAULT NULL,
  `sip_contact_user` varchar(150) DEFAULT NULL,
  `sip_contact_port` varchar(150) DEFAULT NULL,
  `sip_contact_uri` varchar(150) DEFAULT NULL,
  `sip_contact_host` varchar(150) DEFAULT NULL,
  `rtp_use_codec_string` varchar(150) DEFAULT NULL,
  `sip_user_agent` varchar(150) DEFAULT NULL,
  `sip_via_host` varchar(150) DEFAULT NULL,
  `sip_via_port` varchar(150) DEFAULT NULL,
  `sip_via_rport` varchar(150) DEFAULT NULL,
  `switch_r_sdp` text,
  `endpoint_disposition` varchar(150) DEFAULT NULL,
  `effective_caller_id_name` varchar(150) DEFAULT NULL,
  `effective_caller_id_number` varchar(150) DEFAULT NULL,
  `digits_dialed` varchar(150) DEFAULT NULL,
  `start_stamp` varchar(150) DEFAULT NULL,
  `profile_start_stamp` varchar(150) DEFAULT NULL,
  `caller_id` varchar(30) DEFAULT NULL,
  `duration` int(11) DEFAULT NULL,
  `billsec` int(11) DEFAULT NULL,
  `progresssec` int(11) DEFAULT NULL,
  `answersec` int(11) DEFAULT NULL,
  `waitsec` int(11) DEFAULT NULL,
  `flow_billsec` int(11) DEFAULT NULL,
  `sip_hangup_disposition` varchar(30) DEFAULT NULL,
  `in_useragent` varchar(150) DEFAULT NULL,
  `out_useragent` varchar(150) DEFAULT NULL,
  `in_rtp_audio_in_media_bytes` int(11) DEFAULT NULL,
  `in_rtp_audio_out_media_bytes` int(11) DEFAULT NULL,
  `out_rtp_audio_in_media_bytes` int(11) DEFAULT NULL,
  `out_rtp_audio_out_media_bytes` int(11) DEFAULT NULL,
  `rtp_audio_in_media_packet_count` int(11) DEFAULT NULL,
  `rtp_audio_out_media_packet_count` int(11) DEFAULT NULL,
  `in_rtp_audio_in_jitter_packet_count` int(11) DEFAULT NULL,
  `out_rtp_audio_in_jitter_packet_count` int(11) DEFAULT NULL,
  `in_rtp_audio_in_skip_packet_count` int(11) DEFAULT NULL,
  `out_rtp_audio_in_skip_packet_count` int(11) DEFAULT NULL,
  `in_rtp_audio_in_jitter_min_variance` float(20,4) DEFAULT NULL,
  `in_rtp_audio_in_jitter_max_variance` float(20,4) DEFAULT NULL,
  `out_rtp_audio_in_jitter_min_variance` float(20,4) DEFAULT NULL,
  `out_rtp_audio_in_jitter_max_variance` float(20,4) DEFAULT NULL,
  `in_rtp_audio_in_mos` float(6,4) DEFAULT NULL,
  `out_rtp_audio_in_mos` float(6,4) DEFAULT NULL,
  `fscause` varchar(50) DEFAULT NULL,
  `Q850CODE` int(11) DEFAULT NULL,
  `SIPCODE` int(11) DEFAULT NULL,
  `carrier_id` varchar(30) DEFAULT NULL,
  `carrier_ratecard_id` varchar(30) DEFAULT NULL,
  `carrier_tariff_id` varchar(30) DEFAULT NULL,
  `carrier_prefix` varchar(30) DEFAULT NULL,
  `carrier_destination` varchar(30) DEFAULT NULL,
  `carrier_ipaddress` varchar(50) DEFAULT NULL,
  `carrier_ipaddress_name` varchar(30) DEFAULT NULL,
  `carrier_src_caller` varchar(30) DEFAULT NULL,
  `carrier_src_callee` varchar(30) DEFAULT NULL,
  `carrier_dst_caller` varchar(30) DEFAULT NULL,
  `carrier_dst_callee` varchar(30) DEFAULT NULL,
  `customer_tariff_id` varchar(30) DEFAULT NULL,
  `customer_ipaddress` varchar(30) DEFAULT NULL,
  `customer_ratecard_id` varchar(30) DEFAULT NULL,
  `customer_prefix` varchar(30) DEFAULT NULL,
  `customer_destination` varchar(30) DEFAULT NULL,
  `customer_src_caller` varchar(30) DEFAULT NULL,
  `customer_src_callee` varchar(30) DEFAULT NULL,
  `customer_src_ip` varchar(30) DEFAULT NULL,
  `customer_account_id` varchar(30) DEFAULT NULL,
  `reseller1_account_id` varchar(30) DEFAULT NULL,
  `reseller1_tariff_id` varchar(30) DEFAULT NULL,
  `reseller1_ratecard_id` varchar(30) DEFAULT NULL,
  `reseller1_prefix` varchar(20) DEFAULT NULL,
  `reseller1_destination` varchar(50) DEFAULT NULL,
  `reseller2_destination` varchar(50) DEFAULT NULL,
  `reseller2_account_id` varchar(30) DEFAULT NULL,
  `reseller2_tariff_id` varchar(30) DEFAULT NULL,
  `reseller2_ratecard_id` varchar(30) DEFAULT NULL,
  `reseller2_prefix` varchar(20) DEFAULT NULL,
  `reseller3_account_id` varchar(30) DEFAULT NULL,
  `reseller3_tariff_id` varchar(30) DEFAULT NULL,
  `reseller3_ratecard_id` varchar(30) DEFAULT NULL,
  `reseller3_prefix` varchar(20) DEFAULT NULL,
  `reseller3_destination` varchar(50) DEFAULT NULL,
  `fs_errorcode` varchar(40) DEFAULT NULL,
  `hangupby` varchar(40) DEFAULT NULL,
  `end_stamp` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `customer_company_name` varchar(150) DEFAULT NULL,
  `carrier_carrier_name` varchar(150) DEFAULT NULL,
  `customer_incodecs` varchar(300) DEFAULT NULL,
  `carrier_outcodecs` varchar(30) DEFAULT NULL,
  `call_codecs` varchar(30) DEFAULT NULL,
  `cdr_type` varchar(5) DEFAULT 'OUT',
  `data1` varchar(30) DEFAULT NULL,
  `data2` varchar(30) DEFAULT NULL,
  PRIMARY KEY (`id`,`end_stamp`),
  KEY `uuid` (`uuid`) USING BTREE,
  KEY `customer_account_id` (`customer_account_id`) USING BTREE,
  KEY `reseller1_account_id` (`reseller1_account_id`) USING BTREE,
  KEY `reseller2_account_id` (`reseller2_account_id`) USING BTREE,
  KEY `reseller3_account_id` (`reseller3_account_id`) USING BTREE,
  KEY `end_stamp` (`end_stamp`) USING BTREE,
  KEY `billsec` (`billsec`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- ----------------------------
-- Records of 201905_cdr
-- ----------------------------

-- ----------------------------
-- Table structure for `201905_customerstate`
-- ----------------------------
DROP TABLE IF EXISTS `201905_customerstate`;
CREATE TABLE `201905_customerstate` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `account_id` varchar(30) DEFAULT NULL,
  `totalcalls` int(11) DEFAULT '0',
  `answeredcalls` int(11) DEFAULT '0',
  `prefix` varchar(20) DEFAULT NULL,
  `prefix_name` varchar(50) DEFAULT NULL,
  `carrier_id_name` varchar(30) DEFAULT NULL,
  `call_date` date DEFAULT NULL,
  `calltime_h` varchar(5) DEFAULT '0',
  `calltime_m` varchar(5) DEFAULT '0',
  `bill_duration` int(11) DEFAULT '0',
  `account_duration` int(11) DEFAULT '0',
  `account_currency_id` int(11) DEFAULT '0',
  `account_cost` double(12,6) DEFAULT '0.000000',
  `r1_account_id` varchar(30) DEFAULT NULL,
  `r1_duration` int(11) DEFAULT '0',
  `r1_cost` double(12,6) DEFAULT '0.000000',
  `r2_account_id` varchar(30) DEFAULT NULL,
  `r2_duration` int(11) DEFAULT '0',
  `r2_cost` double(12,6) DEFAULT '0.000000',
  `r3_account_id` varchar(30) DEFAULT NULL,
  `r3_duration` int(11) DEFAULT '0',
  `r3_cost` double(12,6) DEFAULT '0.000000',
  `carrier_duration` int(11) DEFAULT '0',
  `carrier_currency_id` int(11) DEFAULT '0',
  `carrier_cost` double(12,6) DEFAULT '0.000000',
  `carrier_prefix` varchar(20) DEFAULT NULL,
  `carrier_prefix_name` varchar(50) DEFAULT NULL,
  `pdd` int(11) DEFAULT '0',
  `fscause` varchar(150) DEFAULT NULL,
  `Q850CODE` int(11) DEFAULT NULL,
  `SIPCODE` int(11) DEFAULT NULL,
  `carrier_callcost_total_usercurrency` double(12,6) DEFAULT '0.000000',
  `carrier_ratio` double(12,6) DEFAULT '1.000000',
  `profit_usercurrency` double(12,6) DEFAULT '0.000000',
  `customer_company_name` varchar(150) DEFAULT NULL,
  `carrier_carrier_name` varchar(150) DEFAULT NULL,
  `src_ipaddress` varchar(30) DEFAULT NULL,
  `cdr_type` varchar(5) DEFAULT 'OUT',
  PRIMARY KEY (`id`),
  UNIQUE KEY `account_id` (`account_id`,`prefix`,`carrier_id_name`,`call_date`,`calltime_h`,`calltime_m`,`r1_account_id`,`r2_account_id`,`r3_account_id`,`Q850CODE`,`SIPCODE`,`src_ipaddress`,`cdr_type`) USING BTREE,
  KEY `call_date` (`call_date`),
  KEY `calltime_h` (`calltime_h`),
  KEY `calltime_m` (`calltime_m`),
  KEY `account_id_2` (`account_id`),
  KEY `carrier_id_name` (`carrier_id_name`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- ----------------------------
-- Records of 201905_customerstate
-- ----------------------------

-- ----------------------------
-- Table structure for `201905_ratedcdr`
-- ----------------------------
DROP TABLE IF EXISTS `201905_ratedcdr`;
CREATE TABLE `201905_ratedcdr` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `uuid` varchar(150) DEFAULT NULL,
  `carrier_ratecard_id` varchar(30) DEFAULT NULL,
  `carrier_tariff_id` varchar(30) DEFAULT NULL,
  `carrier_prefix` varchar(15) DEFAULT NULL,
  `carrier_destination` varchar(50) DEFAULT NULL,
  `carrier_rate` double(10,6) DEFAULT NULL,
  `carrier_connection_charge` double(10,6) DEFAULT NULL,
  `carrier_minimal_time` int(11) DEFAULT NULL,
  `carrier_resolution_time` int(11) DEFAULT NULL,
  `carrier_grace_period` int(11) DEFAULT NULL,
  `carrier_rate_multiplier` double(10,6) DEFAULT NULL,
  `carrier_rate_addition` double(10,6) DEFAULT NULL,
  `carrier_id` varchar(30) DEFAULT NULL,
  `carrier_name` varchar(30) DEFAULT NULL,
  `carrier_ipaddress` varchar(30) DEFAULT NULL,
  `carrier_ipaddress_name` varchar(30) DEFAULT NULL,
  `carrier_currency_id` int(11) DEFAULT NULL,
  `carrier_src_caller` varchar(30) DEFAULT NULL,
  `carrier_src_callee` varchar(30) DEFAULT NULL,
  `carrier_dst_caller` varchar(30) DEFAULT NULL,
  `carrier_dst_callee` varchar(30) DEFAULT NULL,
  `carrier_duration` int(11) DEFAULT NULL,
  `carrier_dp` int(11) DEFAULT NULL,
  `carrier_tax1` double(12,6) DEFAULT '0.000000',
  `carrier_tax2` double(12,6) DEFAULT '0.000000',
  `carrier_tax3` double(12,6) DEFAULT '0.000000',
  `carrier_tax_type` varchar(15) DEFAULT NULL,
  `carrier_callcost` double(10,6) DEFAULT NULL,
  `carrier_tax1_cost` double(12,6) DEFAULT '0.000000',
  `carrier_tax2_cost` double(12,6) DEFAULT '0.000000',
  `carrier_tax3_cost` double(12,6) DEFAULT '0.000000',
  `carrier_callcost_total` double(12,6) DEFAULT '0.000000',
  `carrier_dialplan_id` varchar(30) DEFAULT NULL,
  `customer_account_id` varchar(30) DEFAULT NULL,
  `customer_dp` int(11) DEFAULT NULL,
  `customer_tariff_id` varchar(30) DEFAULT NULL,
  `customer_currency_id` int(11) DEFAULT NULL,
  `customer_ipaddress` varchar(30) DEFAULT NULL,
  `customer_ratecard_id` varchar(30) DEFAULT NULL,
  `customer_prefix` varchar(15) DEFAULT NULL,
  `customer_destination` varchar(50) DEFAULT NULL,
  `customer_rate` double(10,6) DEFAULT NULL,
  `customer_connection_charge` double(10,6) DEFAULT NULL,
  `customer_minimal_time` int(11) DEFAULT NULL,
  `customer_resolution_time` int(11) DEFAULT NULL,
  `customer_grace_period` int(11) DEFAULT NULL,
  `customer_rate_multiplier` double(10,6) DEFAULT NULL,
  `customer_rate_addition` double(10,6) DEFAULT NULL,
  `customer_duration` int(11) DEFAULT NULL,
  `customer_src_caller` varchar(30) DEFAULT NULL,
  `customer_src_callee` varchar(30) DEFAULT NULL,
  `customer_tax1` double(10,6) DEFAULT NULL,
  `customer_tax2` double(10,6) DEFAULT NULL,
  `customer_tax3` double(10,6) DEFAULT NULL,
  `customer_tax1_cost` double(12,6) DEFAULT '0.000000',
  `customer_tax_type` varchar(20) DEFAULT NULL,
  `customer_callcost` double(10,6) DEFAULT NULL,
  `customer_tax2_cost` double(12,6) DEFAULT '0.000000',
  `customer_tax3_cost` double(12,6) DEFAULT '0.000000',
  `customer_callcost_total` double(12,6) DEFAULT '0.000000',
  `customer_src_ip` varchar(30) DEFAULT NULL,
  `reseller1_account_id` varchar(30) DEFAULT NULL,
  `reseller1_tariff_id` varchar(30) DEFAULT NULL,
  `reseller1_dp` int(11) DEFAULT NULL,
  `reseller1_ratecard_id` varchar(30) DEFAULT NULL,
  `reseller1_prefix` varchar(15) DEFAULT NULL,
  `reseller1_destination` varchar(50) DEFAULT NULL,
  `reseller1_rate` double(10,6) DEFAULT NULL,
  `reseller1_connection_charge` double(10,6) DEFAULT NULL,
  `reseller1_minimal_time` int(11) DEFAULT NULL,
  `reseller1_resolution_time` int(11) DEFAULT NULL,
  `reseller1_grace_period` int(11) DEFAULT NULL,
  `reseller1_rate_multiplier` double(10,6) DEFAULT NULL,
  `reseller1_rate_addition` double(10,6) DEFAULT NULL,
  `reseller1_duration` int(11) DEFAULT NULL,
  `reseller1_tax1` double(10,6) DEFAULT NULL,
  `reseller1_tax2` double(10,6) DEFAULT NULL,
  `reseller1_tax3` double(10,6) DEFAULT NULL,
  `reseller1_tax_type` varchar(20) DEFAULT NULL,
  `reseller1_callcost` double(10,6) DEFAULT NULL,
  `reseller1_tax1_cost` double(12,6) DEFAULT '0.000000',
  `reseller1_tax2_cost` double(12,6) DEFAULT '0.000000',
  `reseller1_tax3_cost` double(12,6) DEFAULT '0.000000',
  `reseller1_callcost_total` double(12,6) DEFAULT '0.000000',
  `reseller2_account_id` varchar(30) DEFAULT NULL,
  `reseller2_tariff_id` varchar(30) DEFAULT NULL,
  `reseller2_dp` int(11) DEFAULT NULL,
  `reseller2_ratecard_id` varchar(30) DEFAULT NULL,
  `reseller2_prefix` varchar(15) DEFAULT NULL,
  `reseller2_destination` varchar(50) DEFAULT NULL,
  `reseller2_rate` double(10,6) DEFAULT NULL,
  `reseller2_connection_charge` double(10,6) DEFAULT NULL,
  `reseller2_minimal_time` int(11) DEFAULT NULL,
  `reseller2_resolution_time` int(11) DEFAULT NULL,
  `reseller2_grace_period` int(11) DEFAULT NULL,
  `reseller2_rate_multiplier` double(10,6) DEFAULT NULL,
  `reseller2_rate_addition` double(10,6) DEFAULT NULL,
  `reseller2_duration` int(11) DEFAULT NULL,
  `reseller2_callcost` double(10,6) DEFAULT NULL,
  `reseller2_tax1` double(10,6) DEFAULT NULL,
  `reseller2_tax2` double(10,6) DEFAULT NULL,
  `reseller2_tax3` double(10,6) DEFAULT NULL,
  `reseller2_tax_type` varchar(20) DEFAULT NULL,
  `reseller2_tax1_cost` double(12,6) DEFAULT '0.000000',
  `reseller2_tax2_cost` double(12,6) DEFAULT '0.000000',
  `reseller2_tax3_cost` double(12,6) DEFAULT '0.000000',
  `reseller2_callcost_total` double(12,6) DEFAULT '0.000000',
  `reseller3_account_id` varchar(30) DEFAULT NULL,
  `reseller3_tariff_id` varchar(30) DEFAULT NULL,
  `reseller3_dp` int(11) DEFAULT NULL,
  `reseller3_ratecard_id` varchar(50) DEFAULT NULL,
  `reseller3_prefix` varchar(50) DEFAULT NULL,
  `reseller3_destination` varchar(50) DEFAULT NULL,
  `reseller3_rate` double(10,6) DEFAULT NULL,
  `reseller3_connection_charge` double(10,6) DEFAULT NULL,
  `reseller3_minimal_time` int(11) DEFAULT NULL,
  `reseller3_resolution_time` int(11) DEFAULT NULL,
  `reseller3_grace_period` int(11) DEFAULT NULL,
  `reseller3_rate_multiplier` double(10,6) DEFAULT NULL,
  `reseller3_rate_addition` double(10,6) DEFAULT NULL,
  `reseller3_duration` int(11) DEFAULT NULL,
  `reseller3_tax1` double(10,6) DEFAULT NULL,
  `reseller3_tax2` double(10,6) DEFAULT NULL,
  `reseller3_tax3` double(10,6) DEFAULT NULL,
  `reseller3_tax_type` varchar(30) DEFAULT NULL,
  `reseller3_callcost` double(10,6) DEFAULT NULL,
  `reseller3_tax1_cost` double(12,6) DEFAULT '0.000000',
  `reseller3_tax2_cost` double(12,6) DEFAULT '0.000000',
  `reseller3_tax3_cost` double(12,6) DEFAULT '0.000000',
  `reseller3_callcost_total` double(12,6) DEFAULT '0.000000',
  `customer_actual_callcost` double(12,6) DEFAULT NULL,
  `reseller1_actual_callcost` double(12,6) DEFAULT NULL,
  `reseller2_actual_callcost` double(12,6) DEFAULT NULL,
  `reseller3_actual_callcost` double(12,0) DEFAULT NULL,
  `billsec` int(11) DEFAULT NULL,
  `start_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `answer_time` datetime DEFAULT NULL,
  `end_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `pdd` int(11) DEFAULT NULL,
  `fscause` varchar(50) DEFAULT NULL,
  `Q850CODE` int(11) DEFAULT NULL,
  `SIPCODE` int(11) DEFAULT NULL,
  `caller_callid` varchar(150) DEFAULT NULL,
  `callee_callid` varchar(150) DEFAULT NULL,
  `common_uuid` varchar(150) DEFAULT NULL,
  `hangupby` varchar(20) DEFAULT NULL,
  `customer_balance` varchar(30) DEFAULT NULL,
  `reseller1_balance` varchar(30) DEFAULT NULL,
  `reseller2_balance` varchar(30) DEFAULT NULL,
  `reseller3_balance` varchar(30) DEFAULT NULL,
  `carrier_callcost_total_usercurrency` double(12,6) DEFAULT '0.000000',
  `carrier_ratio` double(12,6) DEFAULT '1.000000',
  `profit_usercurrency` double(12,6) DEFAULT '0.000000',
  `customer_company_name` varchar(150) DEFAULT NULL,
  `customer_incodecs` varchar(300) DEFAULT NULL,
  `carrier_outcodecs` varchar(30) DEFAULT NULL,
  `call_codecs` varchar(30) DEFAULT NULL,
  `data1` varchar(30) DEFAULT NULL,
  `data2` varchar(30) DEFAULT NULL,
  `cdr_type` varchar(5) DEFAULT 'OUT',
  PRIMARY KEY (`id`,`end_time`),
  KEY `customer_account_id` (`customer_account_id`),
  KEY `end_time` (`end_time`),
  KEY `reseller3_account_id` (`reseller3_account_id`),
  KEY `reseller1_account_id` (`reseller1_account_id`),
  KEY `reseller2_account_id` (`reseller2_account_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- ----------------------------
-- Records of 201905_ratedcdr
-- ----------------------------

-- ----------------------------
-- Table structure for `201906_carrierstate`
-- ----------------------------
DROP TABLE IF EXISTS `201906_carrierstate`;
CREATE TABLE `201906_carrierstate` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `carrier_id` varchar(30) DEFAULT NULL,
  `carrier_ipaddress` varchar(30) DEFAULT NULL,
  `bill_duration` int(11) DEFAULT '0',
  `carrier_duration` int(11) DEFAULT '0',
  `carrier_currency_id` int(11) DEFAULT '0',
  `carrier_cost` double(12,6) DEFAULT '0.000000',
  `totalcalls` int(11) DEFAULT '0',
  `answeredcalls` int(11) DEFAULT '0',
  `carrier_prefix` varchar(20) DEFAULT NULL,
  `carrier_prefix_name` varchar(50) DEFAULT NULL,
  `call_date` date DEFAULT NULL,
  `calltime_h` varchar(5) DEFAULT '0',
  `calltime_m` varchar(5) DEFAULT '0',
  `pdd` int(11) DEFAULT '0',
  `fscause` varchar(150) DEFAULT NULL,
  `Q850CODE` int(11) DEFAULT NULL,
  `SIPCODE` int(11) DEFAULT NULL,
  `carrier_name` varchar(150) DEFAULT NULL,
  `cdr_type` varchar(5) DEFAULT 'OUT',
  PRIMARY KEY (`id`),
  UNIQUE KEY `carrier_id_key` (`carrier_id`,`call_date`,`calltime_h`,`calltime_m`,`Q850CODE`,`SIPCODE`,`fscause`,`carrier_ipaddress`,`cdr_type`) USING BTREE,
  KEY `call_date` (`call_date`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- ----------------------------
-- Records of 201906_carrierstate
-- ----------------------------

-- ----------------------------
-- Table structure for `201906_cdr`
-- ----------------------------
DROP TABLE IF EXISTS `201906_cdr`;
CREATE TABLE `201906_cdr` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `common_uuid` varchar(300) DEFAULT NULL,
  `carrier_dialplan_id` varchar(30) DEFAULT NULL,
  `caller_callid` varchar(150) DEFAULT NULL,
  `callee_callid` varchar(150) DEFAULT NULL,
  `uuid` varchar(150) DEFAULT NULL,
  `sip_from_user` varchar(150) DEFAULT NULL,
  `sip_from_uri` varchar(150) DEFAULT NULL,
  `sip_from_host` varchar(150) DEFAULT NULL,
  `channel_name` varchar(150) DEFAULT NULL,
  `sip_call_id` varchar(150) DEFAULT NULL,
  `ep_codec_string` varchar(300) DEFAULT NULL,
  `sip_network_ip` varchar(150) DEFAULT NULL,
  `dialstatus` varchar(30) DEFAULT NULL,
  `sip_received_ip` varchar(30) DEFAULT NULL,
  `sip_received_port` varchar(7) DEFAULT NULL,
  `sip_via_protocol` varchar(30) DEFAULT NULL,
  `sip_from_user_stripped` varchar(150) DEFAULT NULL,
  `sip_from_display` varchar(150) DEFAULT NULL,
  `sip_full_from` varchar(150) DEFAULT NULL,
  `sip_to_display` varchar(30) DEFAULT NULL,
  `sip_full_to` varchar(150) DEFAULT NULL,
  `sip_req_user` varchar(150) DEFAULT NULL,
  `sip_req_uri` varchar(150) DEFAULT NULL,
  `sip_to_user` varchar(150) DEFAULT NULL,
  `sip_to_uri` varchar(150) DEFAULT NULL,
  `sip_contact_user` varchar(150) DEFAULT NULL,
  `sip_contact_port` varchar(150) DEFAULT NULL,
  `sip_contact_uri` varchar(150) DEFAULT NULL,
  `sip_contact_host` varchar(150) DEFAULT NULL,
  `rtp_use_codec_string` varchar(150) DEFAULT NULL,
  `sip_user_agent` varchar(150) DEFAULT NULL,
  `sip_via_host` varchar(150) DEFAULT NULL,
  `sip_via_port` varchar(150) DEFAULT NULL,
  `sip_via_rport` varchar(150) DEFAULT NULL,
  `switch_r_sdp` text,
  `endpoint_disposition` varchar(150) DEFAULT NULL,
  `effective_caller_id_name` varchar(150) DEFAULT NULL,
  `effective_caller_id_number` varchar(150) DEFAULT NULL,
  `digits_dialed` varchar(150) DEFAULT NULL,
  `start_stamp` varchar(150) DEFAULT NULL,
  `profile_start_stamp` varchar(150) DEFAULT NULL,
  `caller_id` varchar(30) DEFAULT NULL,
  `duration` int(11) DEFAULT NULL,
  `billsec` int(11) DEFAULT NULL,
  `progresssec` int(11) DEFAULT NULL,
  `answersec` int(11) DEFAULT NULL,
  `waitsec` int(11) DEFAULT NULL,
  `flow_billsec` int(11) DEFAULT NULL,
  `sip_hangup_disposition` varchar(30) DEFAULT NULL,
  `in_useragent` varchar(150) DEFAULT NULL,
  `out_useragent` varchar(150) DEFAULT NULL,
  `in_rtp_audio_in_media_bytes` int(11) DEFAULT NULL,
  `in_rtp_audio_out_media_bytes` int(11) DEFAULT NULL,
  `out_rtp_audio_in_media_bytes` int(11) DEFAULT NULL,
  `out_rtp_audio_out_media_bytes` int(11) DEFAULT NULL,
  `rtp_audio_in_media_packet_count` int(11) DEFAULT NULL,
  `rtp_audio_out_media_packet_count` int(11) DEFAULT NULL,
  `in_rtp_audio_in_jitter_packet_count` int(11) DEFAULT NULL,
  `out_rtp_audio_in_jitter_packet_count` int(11) DEFAULT NULL,
  `in_rtp_audio_in_skip_packet_count` int(11) DEFAULT NULL,
  `out_rtp_audio_in_skip_packet_count` int(11) DEFAULT NULL,
  `in_rtp_audio_in_jitter_min_variance` float(20,4) DEFAULT NULL,
  `in_rtp_audio_in_jitter_max_variance` float(20,4) DEFAULT NULL,
  `out_rtp_audio_in_jitter_min_variance` float(20,4) DEFAULT NULL,
  `out_rtp_audio_in_jitter_max_variance` float(20,4) DEFAULT NULL,
  `in_rtp_audio_in_mos` float(6,4) DEFAULT NULL,
  `out_rtp_audio_in_mos` float(6,4) DEFAULT NULL,
  `fscause` varchar(50) DEFAULT NULL,
  `Q850CODE` int(11) DEFAULT NULL,
  `SIPCODE` int(11) DEFAULT NULL,
  `carrier_id` varchar(30) DEFAULT NULL,
  `carrier_ratecard_id` varchar(30) DEFAULT NULL,
  `carrier_tariff_id` varchar(30) DEFAULT NULL,
  `carrier_prefix` varchar(30) DEFAULT NULL,
  `carrier_destination` varchar(30) DEFAULT NULL,
  `carrier_ipaddress` varchar(50) DEFAULT NULL,
  `carrier_ipaddress_name` varchar(30) DEFAULT NULL,
  `carrier_src_caller` varchar(30) DEFAULT NULL,
  `carrier_src_callee` varchar(30) DEFAULT NULL,
  `carrier_dst_caller` varchar(30) DEFAULT NULL,
  `carrier_dst_callee` varchar(30) DEFAULT NULL,
  `customer_tariff_id` varchar(30) DEFAULT NULL,
  `customer_ipaddress` varchar(30) DEFAULT NULL,
  `customer_ratecard_id` varchar(30) DEFAULT NULL,
  `customer_prefix` varchar(30) DEFAULT NULL,
  `customer_destination` varchar(30) DEFAULT NULL,
  `customer_src_caller` varchar(30) DEFAULT NULL,
  `customer_src_callee` varchar(30) DEFAULT NULL,
  `customer_src_ip` varchar(30) DEFAULT NULL,
  `customer_account_id` varchar(30) DEFAULT NULL,
  `reseller1_account_id` varchar(30) DEFAULT NULL,
  `reseller1_tariff_id` varchar(30) DEFAULT NULL,
  `reseller1_ratecard_id` varchar(30) DEFAULT NULL,
  `reseller1_prefix` varchar(20) DEFAULT NULL,
  `reseller1_destination` varchar(50) DEFAULT NULL,
  `reseller2_destination` varchar(50) DEFAULT NULL,
  `reseller2_account_id` varchar(30) DEFAULT NULL,
  `reseller2_tariff_id` varchar(30) DEFAULT NULL,
  `reseller2_ratecard_id` varchar(30) DEFAULT NULL,
  `reseller2_prefix` varchar(20) DEFAULT NULL,
  `reseller3_account_id` varchar(30) DEFAULT NULL,
  `reseller3_tariff_id` varchar(30) DEFAULT NULL,
  `reseller3_ratecard_id` varchar(30) DEFAULT NULL,
  `reseller3_prefix` varchar(20) DEFAULT NULL,
  `reseller3_destination` varchar(50) DEFAULT NULL,
  `fs_errorcode` varchar(40) DEFAULT NULL,
  `hangupby` varchar(40) DEFAULT NULL,
  `end_stamp` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `customer_company_name` varchar(150) DEFAULT NULL,
  `carrier_carrier_name` varchar(150) DEFAULT NULL,
  `customer_incodecs` varchar(300) DEFAULT NULL,
  `carrier_outcodecs` varchar(30) DEFAULT NULL,
  `call_codecs` varchar(30) DEFAULT NULL,
  `cdr_type` varchar(5) DEFAULT 'OUT',
  `data1` varchar(30) DEFAULT NULL,
  `data2` varchar(30) DEFAULT NULL,
  PRIMARY KEY (`id`,`end_stamp`),
  KEY `uuid` (`uuid`) USING BTREE,
  KEY `customer_account_id` (`customer_account_id`) USING BTREE,
  KEY `reseller1_account_id` (`reseller1_account_id`) USING BTREE,
  KEY `reseller2_account_id` (`reseller2_account_id`) USING BTREE,
  KEY `reseller3_account_id` (`reseller3_account_id`) USING BTREE,
  KEY `end_stamp` (`end_stamp`) USING BTREE,
  KEY `billsec` (`billsec`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- ----------------------------
-- Records of 201906_cdr
-- ----------------------------

-- ----------------------------
-- Table structure for `201906_customerstate`
-- ----------------------------
DROP TABLE IF EXISTS `201906_customerstate`;
CREATE TABLE `201906_customerstate` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `account_id` varchar(30) DEFAULT NULL,
  `totalcalls` int(11) DEFAULT '0',
  `answeredcalls` int(11) DEFAULT '0',
  `prefix` varchar(20) DEFAULT NULL,
  `prefix_name` varchar(50) DEFAULT NULL,
  `carrier_id` varchar(30) DEFAULT NULL,
  `call_date` date DEFAULT NULL,
  `calltime_h` varchar(5) DEFAULT '0',
  `calltime_m` varchar(5) DEFAULT '0',
  `bill_duration` int(11) DEFAULT '0',
  `customer_duration` int(11) DEFAULT '0',
  `customer_currency_id` int(11) DEFAULT '0',
  `customer_cost` double(12,6) DEFAULT '0.000000',
  `r1_account_id` varchar(30) DEFAULT NULL,
  `r1_duration` int(11) DEFAULT '0',
  `r1_cost` double(12,6) DEFAULT '0.000000',
  `r2_account_id` varchar(30) DEFAULT NULL,
  `r2_duration` int(11) DEFAULT '0',
  `r2_cost` double(12,6) DEFAULT '0.000000',
  `r3_account_id` varchar(30) DEFAULT NULL,
  `r3_duration` int(11) DEFAULT '0',
  `r3_cost` double(12,6) DEFAULT '0.000000',
  `carrier_duration` int(11) DEFAULT '0',
  `carrier_currency_id` int(11) DEFAULT '0',
  `carrier_cost` double(12,6) DEFAULT '0.000000',
  `carrier_prefix` varchar(20) DEFAULT NULL,
  `carrier_prefix_name` varchar(50) DEFAULT NULL,
  `pdd` int(11) DEFAULT '0',
  `fscause` varchar(150) DEFAULT NULL,
  `Q850CODE` int(11) DEFAULT NULL,
  `SIPCODE` int(11) DEFAULT NULL,
  `carrier_callcost_total_usercurrency` double(12,6) DEFAULT '0.000000',
  `carrier_ratio` double(12,6) DEFAULT '1.000000',
  `profit_usercurrency` double(12,6) DEFAULT '0.000000',
  `customer_company_name` varchar(150) DEFAULT NULL,
  `carrier_carrier_name` varchar(150) DEFAULT NULL,
  `src_ipaddress` varchar(30) DEFAULT NULL,
  `cdr_type` varchar(5) DEFAULT 'OUT',
  PRIMARY KEY (`id`),
  UNIQUE KEY `account_id` (`account_id`,`prefix`,`carrier_id`,`call_date`,`calltime_h`,`calltime_m`,`r1_account_id`,`r2_account_id`,`r3_account_id`,`Q850CODE`,`SIPCODE`,`src_ipaddress`,`cdr_type`) USING BTREE,
  KEY `call_date` (`call_date`),
  KEY `calltime_h` (`calltime_h`),
  KEY `calltime_m` (`calltime_m`),
  KEY `account_id_2` (`account_id`),
  KEY `carrier_id` (`carrier_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- ----------------------------
-- Records of 201906_customerstate
-- ----------------------------

-- ----------------------------
-- Table structure for `201906_ratedcdr`
-- ----------------------------
DROP TABLE IF EXISTS `201906_ratedcdr`;
CREATE TABLE `201906_ratedcdr` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `uuid` varchar(150) DEFAULT NULL,
  `carrier_ratecard_id` varchar(30) DEFAULT NULL,
  `carrier_tariff_id` varchar(30) DEFAULT NULL,
  `carrier_prefix` varchar(15) DEFAULT NULL,
  `carrier_destination` varchar(50) DEFAULT NULL,
  `carrier_rate` double(10,6) DEFAULT NULL,
  `carrier_connection_charge` double(10,6) DEFAULT NULL,
  `carrier_minimal_time` int(11) DEFAULT NULL,
  `carrier_resolution_time` int(11) DEFAULT NULL,
  `carrier_grace_period` int(11) DEFAULT NULL,
  `carrier_rate_multiplier` double(10,6) DEFAULT NULL,
  `carrier_rate_addition` double(10,6) DEFAULT NULL,
  `carrier_id` varchar(30) DEFAULT NULL,
  `carrier_name` varchar(30) DEFAULT NULL,
  `carrier_ipaddress` varchar(30) DEFAULT NULL,
  `carrier_ipaddress_name` varchar(30) DEFAULT NULL,
  `carrier_currency_id` int(11) DEFAULT NULL,
  `carrier_src_caller` varchar(30) DEFAULT NULL,
  `carrier_src_callee` varchar(30) DEFAULT NULL,
  `carrier_dst_caller` varchar(30) DEFAULT NULL,
  `carrier_dst_callee` varchar(30) DEFAULT NULL,
  `carrier_duration` int(11) DEFAULT NULL,
  `carrier_dp` int(11) DEFAULT NULL,
  `carrier_tax1` double(12,6) DEFAULT '0.000000',
  `carrier_tax2` double(12,6) DEFAULT '0.000000',
  `carrier_tax3` double(12,6) DEFAULT '0.000000',
  `carrier_tax_type` varchar(15) DEFAULT NULL,
  `carrier_callcost` double(10,6) DEFAULT NULL,
  `carrier_tax1_cost` double(12,6) DEFAULT '0.000000',
  `carrier_tax2_cost` double(12,6) DEFAULT '0.000000',
  `carrier_tax3_cost` double(12,6) DEFAULT '0.000000',
  `carrier_callcost_total` double(12,6) DEFAULT '0.000000',
  `carrier_dialplan_id` varchar(30) DEFAULT NULL,
  `customer_account_id` varchar(30) DEFAULT NULL,
  `customer_dp` int(11) DEFAULT NULL,
  `customer_tariff_id` varchar(30) DEFAULT NULL,
  `customer_currency_id` int(11) DEFAULT NULL,
  `customer_ipaddress` varchar(30) DEFAULT NULL,
  `customer_ratecard_id` varchar(30) DEFAULT NULL,
  `customer_prefix` varchar(15) DEFAULT NULL,
  `customer_destination` varchar(50) DEFAULT NULL,
  `customer_rate` double(10,6) DEFAULT NULL,
  `customer_connection_charge` double(10,6) DEFAULT NULL,
  `customer_minimal_time` int(11) DEFAULT NULL,
  `customer_resolution_time` int(11) DEFAULT NULL,
  `customer_grace_period` int(11) DEFAULT NULL,
  `customer_rate_multiplier` double(10,6) DEFAULT NULL,
  `customer_rate_addition` double(10,6) DEFAULT NULL,
  `customer_duration` int(11) DEFAULT NULL,
  `customer_src_caller` varchar(30) DEFAULT NULL,
  `customer_src_callee` varchar(30) DEFAULT NULL,
  `customer_tax1` double(10,6) DEFAULT NULL,
  `customer_tax2` double(10,6) DEFAULT NULL,
  `customer_tax3` double(10,6) DEFAULT NULL,
  `customer_tax1_cost` double(12,6) DEFAULT '0.000000',
  `customer_tax_type` varchar(20) DEFAULT NULL,
  `customer_callcost` double(10,6) DEFAULT NULL,
  `customer_tax2_cost` double(12,6) DEFAULT '0.000000',
  `customer_tax3_cost` double(12,6) DEFAULT '0.000000',
  `customer_callcost_total` double(12,6) DEFAULT '0.000000',
  `customer_src_ip` varchar(30) DEFAULT NULL,
  `reseller1_account_id` varchar(30) DEFAULT NULL,
  `reseller1_tariff_id` varchar(30) DEFAULT NULL,
  `reseller1_dp` int(11) DEFAULT NULL,
  `reseller1_ratecard_id` varchar(30) DEFAULT NULL,
  `reseller1_prefix` varchar(15) DEFAULT NULL,
  `reseller1_destination` varchar(50) DEFAULT NULL,
  `reseller1_rate` double(10,6) DEFAULT NULL,
  `reseller1_connection_charge` double(10,6) DEFAULT NULL,
  `reseller1_minimal_time` int(11) DEFAULT NULL,
  `reseller1_resolution_time` int(11) DEFAULT NULL,
  `reseller1_grace_period` int(11) DEFAULT NULL,
  `reseller1_rate_multiplier` double(10,6) DEFAULT NULL,
  `reseller1_rate_addition` double(10,6) DEFAULT NULL,
  `reseller1_duration` int(11) DEFAULT NULL,
  `reseller1_tax1` double(10,6) DEFAULT NULL,
  `reseller1_tax2` double(10,6) DEFAULT NULL,
  `reseller1_tax3` double(10,6) DEFAULT NULL,
  `reseller1_tax_type` varchar(20) DEFAULT NULL,
  `reseller1_callcost` double(10,6) DEFAULT NULL,
  `reseller1_tax1_cost` double(12,6) DEFAULT '0.000000',
  `reseller1_tax2_cost` double(12,6) DEFAULT '0.000000',
  `reseller1_tax3_cost` double(12,6) DEFAULT '0.000000',
  `reseller1_callcost_total` double(12,6) DEFAULT '0.000000',
  `reseller2_account_id` varchar(30) DEFAULT NULL,
  `reseller2_tariff_id` varchar(30) DEFAULT NULL,
  `reseller2_dp` int(11) DEFAULT NULL,
  `reseller2_ratecard_id` varchar(30) DEFAULT NULL,
  `reseller2_prefix` varchar(15) DEFAULT NULL,
  `reseller2_destination` varchar(50) DEFAULT NULL,
  `reseller2_rate` double(10,6) DEFAULT NULL,
  `reseller2_connection_charge` double(10,6) DEFAULT NULL,
  `reseller2_minimal_time` int(11) DEFAULT NULL,
  `reseller2_resolution_time` int(11) DEFAULT NULL,
  `reseller2_grace_period` int(11) DEFAULT NULL,
  `reseller2_rate_multiplier` double(10,6) DEFAULT NULL,
  `reseller2_rate_addition` double(10,6) DEFAULT NULL,
  `reseller2_duration` int(11) DEFAULT NULL,
  `reseller2_callcost` double(10,6) DEFAULT NULL,
  `reseller2_tax1` double(10,6) DEFAULT NULL,
  `reseller2_tax2` double(10,6) DEFAULT NULL,
  `reseller2_tax3` double(10,6) DEFAULT NULL,
  `reseller2_tax_type` varchar(20) DEFAULT NULL,
  `reseller2_tax1_cost` double(12,6) DEFAULT '0.000000',
  `reseller2_tax2_cost` double(12,6) DEFAULT '0.000000',
  `reseller2_tax3_cost` double(12,6) DEFAULT '0.000000',
  `reseller2_callcost_total` double(12,6) DEFAULT '0.000000',
  `reseller3_account_id` varchar(30) DEFAULT NULL,
  `reseller3_tariff_id` varchar(30) DEFAULT NULL,
  `reseller3_dp` int(11) DEFAULT NULL,
  `reseller3_ratecard_id` varchar(50) DEFAULT NULL,
  `reseller3_prefix` varchar(50) DEFAULT NULL,
  `reseller3_destination` varchar(50) DEFAULT NULL,
  `reseller3_rate` double(10,6) DEFAULT NULL,
  `reseller3_connection_charge` double(10,6) DEFAULT NULL,
  `reseller3_minimal_time` int(11) DEFAULT NULL,
  `reseller3_resolution_time` int(11) DEFAULT NULL,
  `reseller3_grace_period` int(11) DEFAULT NULL,
  `reseller3_rate_multiplier` double(10,6) DEFAULT NULL,
  `reseller3_rate_addition` double(10,6) DEFAULT NULL,
  `reseller3_duration` int(11) DEFAULT NULL,
  `reseller3_tax1` double(10,6) DEFAULT NULL,
  `reseller3_tax2` double(10,6) DEFAULT NULL,
  `reseller3_tax3` double(10,6) DEFAULT NULL,
  `reseller3_tax_type` varchar(30) DEFAULT NULL,
  `reseller3_callcost` double(10,6) DEFAULT NULL,
  `reseller3_tax1_cost` double(12,6) DEFAULT '0.000000',
  `reseller3_tax2_cost` double(12,6) DEFAULT '0.000000',
  `reseller3_tax3_cost` double(12,6) DEFAULT '0.000000',
  `reseller3_callcost_total` double(12,6) DEFAULT '0.000000',
  `customer_actual_callcost` double(12,6) DEFAULT NULL,
  `reseller1_actual_callcost` double(12,6) DEFAULT NULL,
  `reseller2_actual_callcost` double(12,6) DEFAULT NULL,
  `reseller3_actual_callcost` double(12,0) DEFAULT NULL,
  `billsec` int(11) DEFAULT NULL,
  `start_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `answer_time` datetime DEFAULT NULL,
  `end_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `pdd` int(11) DEFAULT NULL,
  `fscause` varchar(50) DEFAULT NULL,
  `Q850CODE` int(11) DEFAULT NULL,
  `SIPCODE` int(11) DEFAULT NULL,
  `caller_callid` varchar(150) DEFAULT NULL,
  `callee_callid` varchar(150) DEFAULT NULL,
  `common_uuid` varchar(150) DEFAULT NULL,
  `hangupby` varchar(20) DEFAULT NULL,
  `customer_balance` varchar(30) DEFAULT NULL,
  `reseller1_balance` varchar(30) DEFAULT NULL,
  `reseller2_balance` varchar(30) DEFAULT NULL,
  `reseller3_balance` varchar(30) DEFAULT NULL,
  `carrier_callcost_total_usercurrency` double(12,6) DEFAULT '0.000000',
  `carrier_ratio` double(12,6) DEFAULT '1.000000',
  `profit_usercurrency` double(12,6) DEFAULT '0.000000',
  `customer_company_name` varchar(150) DEFAULT NULL,
  `customer_incodecs` varchar(300) DEFAULT NULL,
  `carrier_outcodecs` varchar(30) DEFAULT NULL,
  `call_codecs` varchar(30) DEFAULT NULL,
  `data1` varchar(30) DEFAULT NULL,
  `data2` varchar(30) DEFAULT NULL,
  `cdr_type` varchar(5) DEFAULT 'OUT',
  PRIMARY KEY (`id`,`end_time`),
  KEY `customer_account_id` (`customer_account_id`),
  KEY `end_time` (`end_time`),
  KEY `reseller3_account_id` (`reseller3_account_id`),
  KEY `reseller1_account_id` (`reseller1_account_id`),
  KEY `reseller2_account_id` (`reseller2_account_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- ----------------------------
-- Records of 201906_ratedcdr
-- ----------------------------

-- ----------------------------
-- Table structure for `201907_carrierstate`
-- ----------------------------
DROP TABLE IF EXISTS `201907_carrierstate`;
CREATE TABLE `201907_carrierstate` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `carrier_id` varchar(30) DEFAULT NULL,
  `carrier_ipaddress` varchar(30) DEFAULT NULL,
  `bill_duration` int(11) DEFAULT '0',
  `carrier_duration` int(11) DEFAULT '0',
  `carrier_currency_id` int(11) DEFAULT '0',
  `carrier_cost` double(12,6) DEFAULT '0.000000',
  `totalcalls` int(11) DEFAULT '0',
  `answeredcalls` int(11) DEFAULT '0',
  `carrier_prefix` varchar(20) DEFAULT NULL,
  `carrier_prefix_name` varchar(50) DEFAULT NULL,
  `call_date` date DEFAULT NULL,
  `calltime_h` varchar(5) DEFAULT '0',
  `calltime_m` varchar(5) DEFAULT '0',
  `pdd` int(11) DEFAULT '0',
  `fscause` varchar(150) DEFAULT NULL,
  `Q850CODE` int(11) DEFAULT NULL,
  `SIPCODE` int(11) DEFAULT NULL,
  `carrier_name` varchar(150) DEFAULT NULL,
  `cdr_type` varchar(5) DEFAULT 'OUT',
  PRIMARY KEY (`id`),
  UNIQUE KEY `carrier_id_key` (`carrier_id`,`call_date`,`calltime_h`,`calltime_m`,`Q850CODE`,`SIPCODE`,`fscause`,`carrier_ipaddress`,`cdr_type`) USING BTREE,
  KEY `call_date` (`call_date`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- ----------------------------
-- Records of 201907_carrierstate
-- ----------------------------

-- ----------------------------
-- Table structure for `201907_cdr`
-- ----------------------------
DROP TABLE IF EXISTS `201907_cdr`;
CREATE TABLE `201907_cdr` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `common_uuid` varchar(300) DEFAULT NULL,
  `carrier_dialplan_id` varchar(30) DEFAULT NULL,
  `caller_callid` varchar(150) DEFAULT NULL,
  `callee_callid` varchar(150) DEFAULT NULL,
  `uuid` varchar(150) DEFAULT NULL,
  `sip_from_user` varchar(150) DEFAULT NULL,
  `sip_from_uri` varchar(150) DEFAULT NULL,
  `sip_from_host` varchar(150) DEFAULT NULL,
  `channel_name` varchar(150) DEFAULT NULL,
  `sip_call_id` varchar(150) DEFAULT NULL,
  `ep_codec_string` varchar(300) DEFAULT NULL,
  `sip_network_ip` varchar(150) DEFAULT NULL,
  `dialstatus` varchar(30) DEFAULT NULL,
  `sip_received_ip` varchar(30) DEFAULT NULL,
  `sip_received_port` varchar(7) DEFAULT NULL,
  `sip_via_protocol` varchar(30) DEFAULT NULL,
  `sip_from_user_stripped` varchar(150) DEFAULT NULL,
  `sip_from_display` varchar(150) DEFAULT NULL,
  `sip_full_from` varchar(150) DEFAULT NULL,
  `sip_to_display` varchar(30) DEFAULT NULL,
  `sip_full_to` varchar(150) DEFAULT NULL,
  `sip_req_user` varchar(150) DEFAULT NULL,
  `sip_req_uri` varchar(150) DEFAULT NULL,
  `sip_to_user` varchar(150) DEFAULT NULL,
  `sip_to_uri` varchar(150) DEFAULT NULL,
  `sip_contact_user` varchar(150) DEFAULT NULL,
  `sip_contact_port` varchar(150) DEFAULT NULL,
  `sip_contact_uri` varchar(150) DEFAULT NULL,
  `sip_contact_host` varchar(150) DEFAULT NULL,
  `rtp_use_codec_string` varchar(150) DEFAULT NULL,
  `sip_user_agent` varchar(150) DEFAULT NULL,
  `sip_via_host` varchar(150) DEFAULT NULL,
  `sip_via_port` varchar(150) DEFAULT NULL,
  `sip_via_rport` varchar(150) DEFAULT NULL,
  `switch_r_sdp` text,
  `endpoint_disposition` varchar(150) DEFAULT NULL,
  `effective_caller_id_name` varchar(150) DEFAULT NULL,
  `effective_caller_id_number` varchar(150) DEFAULT NULL,
  `digits_dialed` varchar(150) DEFAULT NULL,
  `start_stamp` varchar(150) DEFAULT NULL,
  `profile_start_stamp` varchar(150) DEFAULT NULL,
  `caller_id` varchar(30) DEFAULT NULL,
  `duration` int(11) DEFAULT NULL,
  `billsec` int(11) DEFAULT NULL,
  `progresssec` int(11) DEFAULT NULL,
  `answersec` int(11) DEFAULT NULL,
  `waitsec` int(11) DEFAULT NULL,
  `flow_billsec` int(11) DEFAULT NULL,
  `sip_hangup_disposition` varchar(30) DEFAULT NULL,
  `in_useragent` varchar(150) DEFAULT NULL,
  `out_useragent` varchar(150) DEFAULT NULL,
  `in_rtp_audio_in_media_bytes` int(11) DEFAULT NULL,
  `in_rtp_audio_out_media_bytes` int(11) DEFAULT NULL,
  `out_rtp_audio_in_media_bytes` int(11) DEFAULT NULL,
  `out_rtp_audio_out_media_bytes` int(11) DEFAULT NULL,
  `rtp_audio_in_media_packet_count` int(11) DEFAULT NULL,
  `rtp_audio_out_media_packet_count` int(11) DEFAULT NULL,
  `in_rtp_audio_in_jitter_packet_count` int(11) DEFAULT NULL,
  `out_rtp_audio_in_jitter_packet_count` int(11) DEFAULT NULL,
  `in_rtp_audio_in_skip_packet_count` int(11) DEFAULT NULL,
  `out_rtp_audio_in_skip_packet_count` int(11) DEFAULT NULL,
  `in_rtp_audio_in_jitter_min_variance` float(20,4) DEFAULT NULL,
  `in_rtp_audio_in_jitter_max_variance` float(20,4) DEFAULT NULL,
  `out_rtp_audio_in_jitter_min_variance` float(20,4) DEFAULT NULL,
  `out_rtp_audio_in_jitter_max_variance` float(20,4) DEFAULT NULL,
  `in_rtp_audio_in_mos` float(6,4) DEFAULT NULL,
  `out_rtp_audio_in_mos` float(6,4) DEFAULT NULL,
  `fscause` varchar(50) DEFAULT NULL,
  `Q850CODE` int(11) DEFAULT NULL,
  `SIPCODE` int(11) DEFAULT NULL,
  `carrier_id` varchar(30) DEFAULT NULL,
  `carrier_ratecard_id` varchar(30) DEFAULT NULL,
  `carrier_tariff_id` varchar(30) DEFAULT NULL,
  `carrier_prefix` varchar(30) DEFAULT NULL,
  `carrier_destination` varchar(30) DEFAULT NULL,
  `carrier_ipaddress` varchar(50) DEFAULT NULL,
  `carrier_ipaddress_name` varchar(30) DEFAULT NULL,
  `carrier_src_caller` varchar(30) DEFAULT NULL,
  `carrier_src_callee` varchar(30) DEFAULT NULL,
  `carrier_dst_caller` varchar(30) DEFAULT NULL,
  `carrier_dst_callee` varchar(30) DEFAULT NULL,
  `customer_tariff_id` varchar(30) DEFAULT NULL,
  `customer_ipaddress` varchar(30) DEFAULT NULL,
  `customer_ratecard_id` varchar(30) DEFAULT NULL,
  `customer_prefix` varchar(30) DEFAULT NULL,
  `customer_destination` varchar(30) DEFAULT NULL,
  `customer_src_caller` varchar(30) DEFAULT NULL,
  `customer_src_callee` varchar(30) DEFAULT NULL,
  `customer_src_ip` varchar(30) DEFAULT NULL,
  `customer_account_id` varchar(30) DEFAULT NULL,
  `reseller1_account_id` varchar(30) DEFAULT NULL,
  `reseller1_tariff_id` varchar(30) DEFAULT NULL,
  `reseller1_ratecard_id` varchar(30) DEFAULT NULL,
  `reseller1_prefix` varchar(20) DEFAULT NULL,
  `reseller1_destination` varchar(50) DEFAULT NULL,
  `reseller2_destination` varchar(50) DEFAULT NULL,
  `reseller2_account_id` varchar(30) DEFAULT NULL,
  `reseller2_tariff_id` varchar(30) DEFAULT NULL,
  `reseller2_ratecard_id` varchar(30) DEFAULT NULL,
  `reseller2_prefix` varchar(20) DEFAULT NULL,
  `reseller3_account_id` varchar(30) DEFAULT NULL,
  `reseller3_tariff_id` varchar(30) DEFAULT NULL,
  `reseller3_ratecard_id` varchar(30) DEFAULT NULL,
  `reseller3_prefix` varchar(20) DEFAULT NULL,
  `reseller3_destination` varchar(50) DEFAULT NULL,
  `fs_errorcode` varchar(40) DEFAULT NULL,
  `hangupby` varchar(40) DEFAULT NULL,
  `end_stamp` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `customer_company_name` varchar(150) DEFAULT NULL,
  `carrier_carrier_name` varchar(150) DEFAULT NULL,
  `customer_incodecs` varchar(300) DEFAULT NULL,
  `carrier_outcodecs` varchar(30) DEFAULT NULL,
  `call_codecs` varchar(30) DEFAULT NULL,
  `cdr_type` varchar(5) DEFAULT 'OUT',
  `data1` varchar(30) DEFAULT NULL,
  `data2` varchar(30) DEFAULT NULL,
  PRIMARY KEY (`id`,`end_stamp`),
  KEY `uuid` (`uuid`) USING BTREE,
  KEY `customer_account_id` (`customer_account_id`) USING BTREE,
  KEY `reseller1_account_id` (`reseller1_account_id`) USING BTREE,
  KEY `reseller2_account_id` (`reseller2_account_id`) USING BTREE,
  KEY `reseller3_account_id` (`reseller3_account_id`) USING BTREE,
  KEY `end_stamp` (`end_stamp`) USING BTREE,
  KEY `billsec` (`billsec`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- ----------------------------
-- Records of 201907_cdr
-- ----------------------------

-- ----------------------------
-- Table structure for `201907_customerstate`
-- ----------------------------
DROP TABLE IF EXISTS `201907_customerstate`;
CREATE TABLE `201907_customerstate` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `account_id` varchar(30) DEFAULT NULL,
  `totalcalls` int(11) DEFAULT '0',
  `answeredcalls` int(11) DEFAULT '0',
  `call_date` date DEFAULT NULL,
  `calltime_h` varchar(5) DEFAULT '0',
  `calltime_m` varchar(5) DEFAULT '0',
  `rate` double(12,6) DEFAULT NULL,
  `prefix` varchar(20) DEFAULT NULL,
  `prefix_name` varchar(50) DEFAULT NULL,
  `bill_duration` int(11) DEFAULT '0',
  `customer_duration` int(11) DEFAULT '0',
  `customer_currency_id` int(11) DEFAULT '0',
  `customer_cost` double(12,6) DEFAULT '0.000000',
  `r1_prefix` varchar(15) DEFAULT NULL,
  `r1_account_id` varchar(30) DEFAULT NULL,
  `r1_rate` double(12,6) DEFAULT NULL,
  `r1_duration` int(11) DEFAULT '0',
  `r1_cost` double(12,6) DEFAULT '0.000000',
  `r2_prefix` varchar(15) DEFAULT NULL,
  `r2_account_id` varchar(30) DEFAULT NULL,
  `r2_rate` double(12,6) DEFAULT NULL,
  `r2_duration` int(11) DEFAULT '0',
  `r2_cost` double(12,6) DEFAULT '0.000000',
  `r3_prefix` varchar(15) DEFAULT NULL,
  `r3_account_id` varchar(30) DEFAULT NULL,
  `r3_rate` double(12,6) DEFAULT NULL,
  `r3_duration` int(11) DEFAULT '0',
  `r3_cost` double(12,6) DEFAULT '0.000000',
  `carrier_prefix` varchar(20) DEFAULT NULL,
  `carrier_ratio` double(12,6) DEFAULT '1.000000',
  `carrier_id` varchar(30) DEFAULT NULL,
  `carrier_duration` int(11) DEFAULT '0',
  `carrier_rate` double(16,6) DEFAULT NULL,
  `carrier_currency_id` int(11) DEFAULT '0',
  `carrier_cost` double(12,6) DEFAULT '0.000000',
  `carrier_prefix_name` varchar(50) DEFAULT NULL,
  `carrier_name` varchar(150) DEFAULT NULL,
  `carrier_callcost_total_usercurrency` double(12,6) DEFAULT '0.000000',
  `customer_company_name` varchar(150) DEFAULT NULL,
  `pdd` int(11) DEFAULT '0',
  `fscause` varchar(150) DEFAULT NULL,
  `Q850CODE` int(11) DEFAULT NULL,
  `SIPCODE` int(11) DEFAULT NULL,
  `profit_usercurrency` double(12,6) DEFAULT '0.000000',
  `src_ipaddress` varchar(30) DEFAULT NULL,
  `cdr_type` varchar(5) DEFAULT 'OUT',
  PRIMARY KEY (`id`),
  UNIQUE KEY `account_id` (`account_id`,`prefix`,`carrier_id`,`call_date`,`calltime_h`,`calltime_m`,`r1_account_id`,`r2_account_id`,`r3_account_id`,`Q850CODE`,`SIPCODE`,`src_ipaddress`,`cdr_type`,`rate`,`r1_prefix`,`r1_rate`,`r2_prefix`,`r2_rate`,`r3_prefix`,`r3_rate`,`carrier_prefix`,`carrier_rate`) USING BTREE,
  KEY `call_date` (`call_date`),
  KEY `calltime_h` (`calltime_h`),
  KEY `calltime_m` (`calltime_m`),
  KEY `account_id_2` (`account_id`),
  KEY `carrier_id` (`carrier_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- ----------------------------
-- Records of 201907_customerstate
-- ----------------------------

-- ----------------------------
-- Table structure for `201907_ratedcdr`
-- ----------------------------
DROP TABLE IF EXISTS `201907_ratedcdr`;
CREATE TABLE `201907_ratedcdr` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `uuid` varchar(150) DEFAULT NULL,
  `carrier_ratecard_id` varchar(30) DEFAULT NULL,
  `carrier_tariff_id` varchar(30) DEFAULT NULL,
  `carrier_prefix` varchar(15) DEFAULT NULL,
  `carrier_destination` varchar(50) DEFAULT NULL,
  `carrier_rate` double(10,6) DEFAULT NULL,
  `carrier_connection_charge` double(10,6) DEFAULT NULL,
  `carrier_minimal_time` int(11) DEFAULT NULL,
  `carrier_resolution_time` int(11) DEFAULT NULL,
  `carrier_grace_period` int(11) DEFAULT NULL,
  `carrier_rate_multiplier` double(10,6) DEFAULT NULL,
  `carrier_rate_addition` double(10,6) DEFAULT NULL,
  `carrier_id` varchar(30) DEFAULT NULL,
  `carrier_name` varchar(30) DEFAULT NULL,
  `carrier_ipaddress` varchar(30) DEFAULT NULL,
  `carrier_ipaddress_name` varchar(30) DEFAULT NULL,
  `carrier_currency_id` int(11) DEFAULT NULL,
  `carrier_src_caller` varchar(30) DEFAULT NULL,
  `carrier_src_callee` varchar(30) DEFAULT NULL,
  `carrier_dst_caller` varchar(30) DEFAULT NULL,
  `carrier_dst_callee` varchar(30) DEFAULT NULL,
  `carrier_duration` int(11) DEFAULT NULL,
  `carrier_dp` int(11) DEFAULT NULL,
  `carrier_tax1` double(12,6) DEFAULT '0.000000',
  `carrier_tax2` double(12,6) DEFAULT '0.000000',
  `carrier_tax3` double(12,6) DEFAULT '0.000000',
  `carrier_tax_type` varchar(15) DEFAULT NULL,
  `carrier_callcost` double(10,6) DEFAULT NULL,
  `carrier_tax1_cost` double(12,6) DEFAULT '0.000000',
  `carrier_tax2_cost` double(12,6) DEFAULT '0.000000',
  `carrier_tax3_cost` double(12,6) DEFAULT '0.000000',
  `carrier_callcost_total` double(12,6) DEFAULT '0.000000',
  `carrier_dialplan_id` varchar(30) DEFAULT NULL,
  `customer_account_id` varchar(30) DEFAULT NULL,
  `customer_dp` int(11) DEFAULT NULL,
  `customer_tariff_id` varchar(30) DEFAULT NULL,
  `customer_currency_id` int(11) DEFAULT NULL,
  `customer_ipaddress` varchar(30) DEFAULT NULL,
  `customer_ratecard_id` varchar(30) DEFAULT NULL,
  `customer_prefix` varchar(15) DEFAULT NULL,
  `customer_destination` varchar(50) DEFAULT NULL,
  `customer_rate` double(10,6) DEFAULT NULL,
  `customer_connection_charge` double(10,6) DEFAULT NULL,
  `customer_minimal_time` int(11) DEFAULT NULL,
  `customer_resolution_time` int(11) DEFAULT NULL,
  `customer_grace_period` int(11) DEFAULT NULL,
  `customer_rate_multiplier` double(10,6) DEFAULT NULL,
  `customer_rate_addition` double(10,6) DEFAULT NULL,
  `customer_duration` int(11) DEFAULT NULL,
  `customer_src_caller` varchar(30) DEFAULT NULL,
  `customer_src_callee` varchar(30) DEFAULT NULL,
  `customer_tax1` double(10,6) DEFAULT NULL,
  `customer_tax2` double(10,6) DEFAULT NULL,
  `customer_tax3` double(10,6) DEFAULT NULL,
  `customer_tax1_cost` double(12,6) DEFAULT '0.000000',
  `customer_tax_type` varchar(20) DEFAULT NULL,
  `customer_callcost` double(10,6) DEFAULT NULL,
  `customer_tax2_cost` double(12,6) DEFAULT '0.000000',
  `customer_tax3_cost` double(12,6) DEFAULT '0.000000',
  `customer_callcost_total` double(12,6) DEFAULT '0.000000',
  `customer_src_ip` varchar(30) DEFAULT NULL,
  `reseller1_account_id` varchar(30) DEFAULT NULL,
  `reseller1_tariff_id` varchar(30) DEFAULT NULL,
  `reseller1_dp` int(11) DEFAULT NULL,
  `reseller1_ratecard_id` varchar(30) DEFAULT NULL,
  `reseller1_prefix` varchar(15) DEFAULT NULL,
  `reseller1_destination` varchar(50) DEFAULT NULL,
  `reseller1_rate` double(10,6) DEFAULT NULL,
  `reseller1_connection_charge` double(10,6) DEFAULT NULL,
  `reseller1_minimal_time` int(11) DEFAULT NULL,
  `reseller1_resolution_time` int(11) DEFAULT NULL,
  `reseller1_grace_period` int(11) DEFAULT NULL,
  `reseller1_rate_multiplier` double(10,6) DEFAULT NULL,
  `reseller1_rate_addition` double(10,6) DEFAULT NULL,
  `reseller1_duration` int(11) DEFAULT NULL,
  `reseller1_tax1` double(10,6) DEFAULT NULL,
  `reseller1_tax2` double(10,6) DEFAULT NULL,
  `reseller1_tax3` double(10,6) DEFAULT NULL,
  `reseller1_tax_type` varchar(20) DEFAULT NULL,
  `reseller1_callcost` double(10,6) DEFAULT NULL,
  `reseller1_tax1_cost` double(12,6) DEFAULT '0.000000',
  `reseller1_tax2_cost` double(12,6) DEFAULT '0.000000',
  `reseller1_tax3_cost` double(12,6) DEFAULT '0.000000',
  `reseller1_callcost_total` double(12,6) DEFAULT '0.000000',
  `reseller2_account_id` varchar(30) DEFAULT NULL,
  `reseller2_tariff_id` varchar(30) DEFAULT NULL,
  `reseller2_dp` int(11) DEFAULT NULL,
  `reseller2_ratecard_id` varchar(30) DEFAULT NULL,
  `reseller2_prefix` varchar(15) DEFAULT NULL,
  `reseller2_destination` varchar(50) DEFAULT NULL,
  `reseller2_rate` double(10,6) DEFAULT NULL,
  `reseller2_connection_charge` double(10,6) DEFAULT NULL,
  `reseller2_minimal_time` int(11) DEFAULT NULL,
  `reseller2_resolution_time` int(11) DEFAULT NULL,
  `reseller2_grace_period` int(11) DEFAULT NULL,
  `reseller2_rate_multiplier` double(10,6) DEFAULT NULL,
  `reseller2_rate_addition` double(10,6) DEFAULT NULL,
  `reseller2_duration` int(11) DEFAULT NULL,
  `reseller2_callcost` double(10,6) DEFAULT NULL,
  `reseller2_tax1` double(10,6) DEFAULT NULL,
  `reseller2_tax2` double(10,6) DEFAULT NULL,
  `reseller2_tax3` double(10,6) DEFAULT NULL,
  `reseller2_tax_type` varchar(20) DEFAULT NULL,
  `reseller2_tax1_cost` double(12,6) DEFAULT '0.000000',
  `reseller2_tax2_cost` double(12,6) DEFAULT '0.000000',
  `reseller2_tax3_cost` double(12,6) DEFAULT '0.000000',
  `reseller2_callcost_total` double(12,6) DEFAULT '0.000000',
  `reseller3_account_id` varchar(30) DEFAULT NULL,
  `reseller3_tariff_id` varchar(30) DEFAULT NULL,
  `reseller3_dp` int(11) DEFAULT NULL,
  `reseller3_ratecard_id` varchar(50) DEFAULT NULL,
  `reseller3_prefix` varchar(50) DEFAULT NULL,
  `reseller3_destination` varchar(50) DEFAULT NULL,
  `reseller3_rate` double(10,6) DEFAULT NULL,
  `reseller3_connection_charge` double(10,6) DEFAULT NULL,
  `reseller3_minimal_time` int(11) DEFAULT NULL,
  `reseller3_resolution_time` int(11) DEFAULT NULL,
  `reseller3_grace_period` int(11) DEFAULT NULL,
  `reseller3_rate_multiplier` double(10,6) DEFAULT NULL,
  `reseller3_rate_addition` double(10,6) DEFAULT NULL,
  `reseller3_duration` int(11) DEFAULT NULL,
  `reseller3_tax1` double(10,6) DEFAULT NULL,
  `reseller3_tax2` double(10,6) DEFAULT NULL,
  `reseller3_tax3` double(10,6) DEFAULT NULL,
  `reseller3_tax_type` varchar(30) DEFAULT NULL,
  `reseller3_callcost` double(10,6) DEFAULT NULL,
  `reseller3_tax1_cost` double(12,6) DEFAULT '0.000000',
  `reseller3_tax2_cost` double(12,6) DEFAULT '0.000000',
  `reseller3_tax3_cost` double(12,6) DEFAULT '0.000000',
  `reseller3_callcost_total` double(12,6) DEFAULT '0.000000',
  `customer_actual_callcost` double(12,6) DEFAULT NULL,
  `reseller1_actual_callcost` double(12,6) DEFAULT NULL,
  `reseller2_actual_callcost` double(12,6) DEFAULT NULL,
  `reseller3_actual_callcost` double(12,0) DEFAULT NULL,
  `billsec` int(11) DEFAULT NULL,
  `start_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `answer_time` datetime DEFAULT NULL,
  `end_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `pdd` int(11) DEFAULT NULL,
  `fscause` varchar(50) DEFAULT NULL,
  `Q850CODE` int(11) DEFAULT NULL,
  `SIPCODE` int(11) DEFAULT NULL,
  `caller_callid` varchar(150) DEFAULT NULL,
  `callee_callid` varchar(150) DEFAULT NULL,
  `common_uuid` varchar(150) DEFAULT NULL,
  `hangupby` varchar(20) DEFAULT NULL,
  `customer_balance` varchar(30) DEFAULT NULL,
  `reseller1_balance` varchar(30) DEFAULT NULL,
  `reseller2_balance` varchar(30) DEFAULT NULL,
  `reseller3_balance` varchar(30) DEFAULT NULL,
  `carrier_callcost_total_usercurrency` double(12,6) DEFAULT '0.000000',
  `carrier_ratio` double(12,6) DEFAULT '1.000000',
  `profit_usercurrency` double(12,6) DEFAULT '0.000000',
  `customer_company_name` varchar(150) DEFAULT NULL,
  `customer_incodecs` varchar(300) DEFAULT NULL,
  `carrier_outcodecs` varchar(30) DEFAULT NULL,
  `call_codecs` varchar(30) DEFAULT NULL,
  `data1` varchar(30) DEFAULT NULL,
  `data2` varchar(30) DEFAULT NULL,
  `cdr_type` varchar(5) DEFAULT 'OUT',
  PRIMARY KEY (`id`,`end_time`),
  KEY `customer_account_id` (`customer_account_id`),
  KEY `end_time` (`end_time`),
  KEY `reseller3_account_id` (`reseller3_account_id`),
  KEY `reseller1_account_id` (`reseller1_account_id`),
  KEY `reseller2_account_id` (`reseller2_account_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- ----------------------------
-- Records of 201907_ratedcdr
-- ----------------------------

-- ----------------------------
-- Table structure for `201908_carrierstate`
-- ----------------------------
DROP TABLE IF EXISTS `201908_carrierstate`;
CREATE TABLE `201908_carrierstate` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `carrier_id` varchar(30) DEFAULT NULL,
  `carrier_ipaddress` varchar(30) DEFAULT NULL,
  `bill_duration` int(11) DEFAULT '0',
  `carrier_duration` int(11) DEFAULT '0',
  `carrier_currency_id` int(11) DEFAULT '0',
  `carrier_cost` double(12,6) DEFAULT '0.000000',
  `totalcalls` int(11) DEFAULT '0',
  `answeredcalls` int(11) DEFAULT '0',
  `carrier_prefix` varchar(20) DEFAULT NULL,
  `carrier_prefix_name` varchar(50) DEFAULT NULL,
  `call_date` date DEFAULT NULL,
  `calltime_h` varchar(5) DEFAULT '0',
  `calltime_m` varchar(5) DEFAULT '0',
  `pdd` int(11) DEFAULT '0',
  `fscause` varchar(150) DEFAULT NULL,
  `Q850CODE` int(11) DEFAULT NULL,
  `SIPCODE` int(11) DEFAULT NULL,
  `carrier_name` varchar(150) DEFAULT NULL,
  `cdr_type` varchar(5) DEFAULT 'OUT',
  PRIMARY KEY (`id`),
  UNIQUE KEY `carrier_id_key` (`carrier_id`,`call_date`,`calltime_h`,`calltime_m`,`Q850CODE`,`SIPCODE`,`fscause`,`carrier_ipaddress`,`cdr_type`) USING BTREE,
  KEY `call_date` (`call_date`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- ----------------------------
-- Records of 201908_carrierstate
-- ----------------------------

-- ----------------------------
-- Table structure for `201908_cdr`
-- ----------------------------
DROP TABLE IF EXISTS `201908_cdr`;
CREATE TABLE `201908_cdr` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `common_uuid` varchar(300) DEFAULT NULL,
  `carrier_dialplan_id` varchar(30) DEFAULT NULL,
  `caller_callid` varchar(150) DEFAULT NULL,
  `callee_callid` varchar(150) DEFAULT NULL,
  `uuid` varchar(150) DEFAULT NULL,
  `sip_from_user` varchar(150) DEFAULT NULL,
  `sip_from_uri` varchar(150) DEFAULT NULL,
  `sip_from_host` varchar(150) DEFAULT NULL,
  `channel_name` varchar(150) DEFAULT NULL,
  `sip_call_id` varchar(150) DEFAULT NULL,
  `ep_codec_string` varchar(300) DEFAULT NULL,
  `sip_network_ip` varchar(150) DEFAULT NULL,
  `dialstatus` varchar(30) DEFAULT NULL,
  `sip_received_ip` varchar(30) DEFAULT NULL,
  `sip_received_port` varchar(7) DEFAULT NULL,
  `sip_via_protocol` varchar(30) DEFAULT NULL,
  `sip_from_user_stripped` varchar(150) DEFAULT NULL,
  `sip_from_display` varchar(150) DEFAULT NULL,
  `sip_full_from` varchar(150) DEFAULT NULL,
  `sip_to_display` varchar(30) DEFAULT NULL,
  `sip_full_to` varchar(150) DEFAULT NULL,
  `sip_req_user` varchar(150) DEFAULT NULL,
  `sip_req_uri` varchar(150) DEFAULT NULL,
  `sip_to_user` varchar(150) DEFAULT NULL,
  `sip_to_uri` varchar(150) DEFAULT NULL,
  `sip_contact_user` varchar(150) DEFAULT NULL,
  `sip_contact_port` varchar(150) DEFAULT NULL,
  `sip_contact_uri` varchar(150) DEFAULT NULL,
  `sip_contact_host` varchar(150) DEFAULT NULL,
  `rtp_use_codec_string` varchar(150) DEFAULT NULL,
  `sip_user_agent` varchar(150) DEFAULT NULL,
  `sip_via_host` varchar(150) DEFAULT NULL,
  `sip_via_port` varchar(150) DEFAULT NULL,
  `sip_via_rport` varchar(150) DEFAULT NULL,
  `switch_r_sdp` text,
  `endpoint_disposition` varchar(150) DEFAULT NULL,
  `effective_caller_id_name` varchar(150) DEFAULT NULL,
  `effective_caller_id_number` varchar(150) DEFAULT NULL,
  `digits_dialed` varchar(150) DEFAULT NULL,
  `start_stamp` varchar(150) DEFAULT NULL,
  `profile_start_stamp` varchar(150) DEFAULT NULL,
  `caller_id` varchar(30) DEFAULT NULL,
  `duration` int(11) DEFAULT NULL,
  `billsec` int(11) DEFAULT NULL,
  `progresssec` int(11) DEFAULT NULL,
  `answersec` int(11) DEFAULT NULL,
  `waitsec` int(11) DEFAULT NULL,
  `flow_billsec` int(11) DEFAULT NULL,
  `sip_hangup_disposition` varchar(30) DEFAULT NULL,
  `in_useragent` varchar(150) DEFAULT NULL,
  `out_useragent` varchar(150) DEFAULT NULL,
  `in_rtp_audio_in_media_bytes` int(11) DEFAULT NULL,
  `in_rtp_audio_out_media_bytes` int(11) DEFAULT NULL,
  `out_rtp_audio_in_media_bytes` int(11) DEFAULT NULL,
  `out_rtp_audio_out_media_bytes` int(11) DEFAULT NULL,
  `rtp_audio_in_media_packet_count` int(11) DEFAULT NULL,
  `rtp_audio_out_media_packet_count` int(11) DEFAULT NULL,
  `in_rtp_audio_in_jitter_packet_count` int(11) DEFAULT NULL,
  `out_rtp_audio_in_jitter_packet_count` int(11) DEFAULT NULL,
  `in_rtp_audio_in_skip_packet_count` int(11) DEFAULT NULL,
  `out_rtp_audio_in_skip_packet_count` int(11) DEFAULT NULL,
  `in_rtp_audio_in_jitter_min_variance` float(20,4) DEFAULT NULL,
  `in_rtp_audio_in_jitter_max_variance` float(20,4) DEFAULT NULL,
  `out_rtp_audio_in_jitter_min_variance` float(20,4) DEFAULT NULL,
  `out_rtp_audio_in_jitter_max_variance` float(20,4) DEFAULT NULL,
  `in_rtp_audio_in_mos` float(6,4) DEFAULT NULL,
  `out_rtp_audio_in_mos` float(6,4) DEFAULT NULL,
  `fscause` varchar(50) DEFAULT NULL,
  `Q850CODE` int(11) DEFAULT NULL,
  `SIPCODE` int(11) DEFAULT NULL,
  `carrier_id` varchar(30) DEFAULT NULL,
  `carrier_ratecard_id` varchar(30) DEFAULT NULL,
  `carrier_tariff_id` varchar(30) DEFAULT NULL,
  `carrier_prefix` varchar(30) DEFAULT NULL,
  `carrier_destination` varchar(30) DEFAULT NULL,
  `carrier_ipaddress` varchar(50) DEFAULT NULL,
  `carrier_ipaddress_name` varchar(30) DEFAULT NULL,
  `carrier_src_caller` varchar(30) DEFAULT NULL,
  `carrier_src_callee` varchar(30) DEFAULT NULL,
  `carrier_dst_caller` varchar(30) DEFAULT NULL,
  `carrier_dst_callee` varchar(30) DEFAULT NULL,
  `customer_tariff_id` varchar(30) DEFAULT NULL,
  `customer_ipaddress` varchar(30) DEFAULT NULL,
  `customer_ratecard_id` varchar(30) DEFAULT NULL,
  `customer_prefix` varchar(30) DEFAULT NULL,
  `customer_destination` varchar(30) DEFAULT NULL,
  `customer_src_caller` varchar(30) DEFAULT NULL,
  `customer_src_callee` varchar(30) DEFAULT NULL,
  `customer_src_ip` varchar(30) DEFAULT NULL,
  `customer_account_id` varchar(30) DEFAULT NULL,
  `reseller1_account_id` varchar(30) DEFAULT NULL,
  `reseller1_tariff_id` varchar(30) DEFAULT NULL,
  `reseller1_ratecard_id` varchar(30) DEFAULT NULL,
  `reseller1_prefix` varchar(20) DEFAULT NULL,
  `reseller1_destination` varchar(50) DEFAULT NULL,
  `reseller2_destination` varchar(50) DEFAULT NULL,
  `reseller2_account_id` varchar(30) DEFAULT NULL,
  `reseller2_tariff_id` varchar(30) DEFAULT NULL,
  `reseller2_ratecard_id` varchar(30) DEFAULT NULL,
  `reseller2_prefix` varchar(20) DEFAULT NULL,
  `reseller3_account_id` varchar(30) DEFAULT NULL,
  `reseller3_tariff_id` varchar(30) DEFAULT NULL,
  `reseller3_ratecard_id` varchar(30) DEFAULT NULL,
  `reseller3_prefix` varchar(20) DEFAULT NULL,
  `reseller3_destination` varchar(50) DEFAULT NULL,
  `fs_errorcode` varchar(40) DEFAULT NULL,
  `hangupby` varchar(40) DEFAULT NULL,
  `end_stamp` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `customer_company_name` varchar(150) DEFAULT NULL,
  `carrier_carrier_name` varchar(150) DEFAULT NULL,
  `customer_incodecs` varchar(300) DEFAULT NULL,
  `carrier_outcodecs` varchar(30) DEFAULT NULL,
  `call_codecs` varchar(30) DEFAULT NULL,
  `cdr_type` varchar(5) DEFAULT 'OUT',
  `data1` varchar(30) DEFAULT NULL,
  `data2` varchar(30) DEFAULT NULL,
  PRIMARY KEY (`id`,`end_stamp`),
  KEY `uuid` (`uuid`) USING BTREE,
  KEY `customer_account_id` (`customer_account_id`) USING BTREE,
  KEY `reseller1_account_id` (`reseller1_account_id`) USING BTREE,
  KEY `reseller2_account_id` (`reseller2_account_id`) USING BTREE,
  KEY `reseller3_account_id` (`reseller3_account_id`) USING BTREE,
  KEY `end_stamp` (`end_stamp`) USING BTREE,
  KEY `billsec` (`billsec`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- ----------------------------
-- Records of 201908_cdr
-- ----------------------------

-- ----------------------------
-- Table structure for `201908_customerstate`
-- ----------------------------
DROP TABLE IF EXISTS `201908_customerstate`;
CREATE TABLE `201908_customerstate` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `account_id` varchar(30) DEFAULT NULL,
  `totalcalls` int(11) DEFAULT '0',
  `answeredcalls` int(11) DEFAULT '0',
  `call_date` date DEFAULT NULL,
  `calltime_h` varchar(5) DEFAULT '0',
  `calltime_m` varchar(5) DEFAULT '0',
  `rate` double(12,6) DEFAULT NULL,
  `prefix` varchar(20) DEFAULT NULL,
  `prefix_name` varchar(50) DEFAULT NULL,
  `bill_duration` int(11) DEFAULT '0',
  `customer_duration` int(11) DEFAULT '0',
  `customer_currency_id` int(11) DEFAULT '0',
  `customer_cost` double(12,6) DEFAULT '0.000000',
  `r1_prefix` varchar(15) DEFAULT NULL,
  `r1_account_id` varchar(30) DEFAULT NULL,
  `r1_rate` double(12,6) DEFAULT NULL,
  `r1_duration` int(11) DEFAULT '0',
  `r1_cost` double(12,6) DEFAULT '0.000000',
  `r2_prefix` varchar(15) DEFAULT NULL,
  `r2_account_id` varchar(30) DEFAULT NULL,
  `r2_rate` double(12,6) DEFAULT NULL,
  `r2_duration` int(11) DEFAULT '0',
  `r2_cost` double(12,6) DEFAULT '0.000000',
  `r3_prefix` varchar(15) DEFAULT NULL,
  `r3_account_id` varchar(30) DEFAULT NULL,
  `r3_rate` double(12,6) DEFAULT NULL,
  `r3_duration` int(11) DEFAULT '0',
  `r3_cost` double(12,6) DEFAULT '0.000000',
  `carrier_prefix` varchar(20) DEFAULT NULL,
  `carrier_ratio` double(12,6) DEFAULT '1.000000',
  `carrier_id` varchar(30) DEFAULT NULL,
  `carrier_duration` int(11) DEFAULT '0',
  `carrier_rate` double(16,6) DEFAULT NULL,
  `carrier_currency_id` int(11) DEFAULT '0',
  `carrier_cost` double(12,6) DEFAULT '0.000000',
  `carrier_prefix_name` varchar(50) DEFAULT NULL,
  `carrier_name` varchar(150) DEFAULT NULL,
  `carrier_callcost_total_usercurrency` double(12,6) DEFAULT '0.000000',
  `customer_company_name` varchar(150) DEFAULT NULL,
  `pdd` int(11) DEFAULT '0',
  `fscause` varchar(150) DEFAULT NULL,
  `Q850CODE` int(11) DEFAULT NULL,
  `SIPCODE` int(11) DEFAULT NULL,
  `profit_usercurrency` double(12,6) DEFAULT '0.000000',
  `src_ipaddress` varchar(30) DEFAULT NULL,
  `cdr_type` varchar(5) DEFAULT 'OUT',
  PRIMARY KEY (`id`),
  UNIQUE KEY `account_id` (`account_id`,`prefix`,`carrier_id`,`call_date`,`calltime_h`,`calltime_m`,`r1_account_id`,`r2_account_id`,`r3_account_id`,`Q850CODE`,`SIPCODE`,`src_ipaddress`,`cdr_type`,`rate`,`r1_prefix`,`r1_rate`,`r2_prefix`,`r2_rate`,`r3_prefix`,`r3_rate`,`carrier_prefix`,`carrier_rate`) USING BTREE,
  KEY `call_date` (`call_date`),
  KEY `calltime_h` (`calltime_h`),
  KEY `calltime_m` (`calltime_m`),
  KEY `account_id_2` (`account_id`),
  KEY `carrier_id` (`carrier_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- ----------------------------
-- Records of 201908_customerstate
-- ----------------------------

-- ----------------------------
-- Table structure for `201908_ratedcdr`
-- ----------------------------
DROP TABLE IF EXISTS `201908_ratedcdr`;
CREATE TABLE `201908_ratedcdr` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `uuid` varchar(150) DEFAULT NULL,
  `carrier_ratecard_id` varchar(30) DEFAULT NULL,
  `carrier_tariff_id` varchar(30) DEFAULT NULL,
  `carrier_prefix` varchar(15) DEFAULT NULL,
  `carrier_destination` varchar(50) DEFAULT NULL,
  `carrier_rate` double(10,6) DEFAULT NULL,
  `carrier_connection_charge` double(10,6) DEFAULT NULL,
  `carrier_minimal_time` int(11) DEFAULT NULL,
  `carrier_resolution_time` int(11) DEFAULT NULL,
  `carrier_grace_period` int(11) DEFAULT NULL,
  `carrier_rate_multiplier` double(10,6) DEFAULT NULL,
  `carrier_rate_addition` double(10,6) DEFAULT NULL,
  `carrier_id` varchar(30) DEFAULT NULL,
  `carrier_name` varchar(30) DEFAULT NULL,
  `carrier_ipaddress` varchar(30) DEFAULT NULL,
  `carrier_ipaddress_name` varchar(30) DEFAULT NULL,
  `carrier_currency_id` int(11) DEFAULT NULL,
  `carrier_src_caller` varchar(30) DEFAULT NULL,
  `carrier_src_callee` varchar(30) DEFAULT NULL,
  `carrier_dst_caller` varchar(30) DEFAULT NULL,
  `carrier_dst_callee` varchar(30) DEFAULT NULL,
  `carrier_duration` int(11) DEFAULT NULL,
  `carrier_dp` int(11) DEFAULT NULL,
  `carrier_tax1` double(12,6) DEFAULT '0.000000',
  `carrier_tax2` double(12,6) DEFAULT '0.000000',
  `carrier_tax3` double(12,6) DEFAULT '0.000000',
  `carrier_tax_type` varchar(15) DEFAULT NULL,
  `carrier_callcost` double(10,6) DEFAULT NULL,
  `carrier_tax1_cost` double(12,6) DEFAULT '0.000000',
  `carrier_tax2_cost` double(12,6) DEFAULT '0.000000',
  `carrier_tax3_cost` double(12,6) DEFAULT '0.000000',
  `carrier_callcost_total` double(12,6) DEFAULT '0.000000',
  `carrier_dialplan_id` varchar(30) DEFAULT NULL,
  `customer_account_id` varchar(30) DEFAULT NULL,
  `customer_dp` int(11) DEFAULT NULL,
  `customer_tariff_id` varchar(30) DEFAULT NULL,
  `customer_currency_id` int(11) DEFAULT NULL,
  `customer_ipaddress` varchar(30) DEFAULT NULL,
  `customer_ratecard_id` varchar(30) DEFAULT NULL,
  `customer_prefix` varchar(15) DEFAULT NULL,
  `customer_destination` varchar(50) DEFAULT NULL,
  `customer_rate` double(10,6) DEFAULT NULL,
  `customer_connection_charge` double(10,6) DEFAULT NULL,
  `customer_minimal_time` int(11) DEFAULT NULL,
  `customer_resolution_time` int(11) DEFAULT NULL,
  `customer_grace_period` int(11) DEFAULT NULL,
  `customer_rate_multiplier` double(10,6) DEFAULT NULL,
  `customer_rate_addition` double(10,6) DEFAULT NULL,
  `customer_duration` int(11) DEFAULT NULL,
  `customer_src_caller` varchar(30) DEFAULT NULL,
  `customer_src_callee` varchar(30) DEFAULT NULL,
  `customer_tax1` double(10,6) DEFAULT NULL,
  `customer_tax2` double(10,6) DEFAULT NULL,
  `customer_tax3` double(10,6) DEFAULT NULL,
  `customer_tax1_cost` double(12,6) DEFAULT '0.000000',
  `customer_tax_type` varchar(20) DEFAULT NULL,
  `customer_callcost` double(10,6) DEFAULT NULL,
  `customer_tax2_cost` double(12,6) DEFAULT '0.000000',
  `customer_tax3_cost` double(12,6) DEFAULT '0.000000',
  `customer_callcost_total` double(12,6) DEFAULT '0.000000',
  `customer_src_ip` varchar(30) DEFAULT NULL,
  `reseller1_account_id` varchar(30) DEFAULT NULL,
  `reseller1_tariff_id` varchar(30) DEFAULT NULL,
  `reseller1_dp` int(11) DEFAULT NULL,
  `reseller1_ratecard_id` varchar(30) DEFAULT NULL,
  `reseller1_prefix` varchar(15) DEFAULT NULL,
  `reseller1_destination` varchar(50) DEFAULT NULL,
  `reseller1_rate` double(10,6) DEFAULT NULL,
  `reseller1_connection_charge` double(10,6) DEFAULT NULL,
  `reseller1_minimal_time` int(11) DEFAULT NULL,
  `reseller1_resolution_time` int(11) DEFAULT NULL,
  `reseller1_grace_period` int(11) DEFAULT NULL,
  `reseller1_rate_multiplier` double(10,6) DEFAULT NULL,
  `reseller1_rate_addition` double(10,6) DEFAULT NULL,
  `reseller1_duration` int(11) DEFAULT NULL,
  `reseller1_tax1` double(10,6) DEFAULT NULL,
  `reseller1_tax2` double(10,6) DEFAULT NULL,
  `reseller1_tax3` double(10,6) DEFAULT NULL,
  `reseller1_tax_type` varchar(20) DEFAULT NULL,
  `reseller1_callcost` double(10,6) DEFAULT NULL,
  `reseller1_tax1_cost` double(12,6) DEFAULT '0.000000',
  `reseller1_tax2_cost` double(12,6) DEFAULT '0.000000',
  `reseller1_tax3_cost` double(12,6) DEFAULT '0.000000',
  `reseller1_callcost_total` double(12,6) DEFAULT '0.000000',
  `reseller2_account_id` varchar(30) DEFAULT NULL,
  `reseller2_tariff_id` varchar(30) DEFAULT NULL,
  `reseller2_dp` int(11) DEFAULT NULL,
  `reseller2_ratecard_id` varchar(30) DEFAULT NULL,
  `reseller2_prefix` varchar(15) DEFAULT NULL,
  `reseller2_destination` varchar(50) DEFAULT NULL,
  `reseller2_rate` double(10,6) DEFAULT NULL,
  `reseller2_connection_charge` double(10,6) DEFAULT NULL,
  `reseller2_minimal_time` int(11) DEFAULT NULL,
  `reseller2_resolution_time` int(11) DEFAULT NULL,
  `reseller2_grace_period` int(11) DEFAULT NULL,
  `reseller2_rate_multiplier` double(10,6) DEFAULT NULL,
  `reseller2_rate_addition` double(10,6) DEFAULT NULL,
  `reseller2_duration` int(11) DEFAULT NULL,
  `reseller2_callcost` double(10,6) DEFAULT NULL,
  `reseller2_tax1` double(10,6) DEFAULT NULL,
  `reseller2_tax2` double(10,6) DEFAULT NULL,
  `reseller2_tax3` double(10,6) DEFAULT NULL,
  `reseller2_tax_type` varchar(20) DEFAULT NULL,
  `reseller2_tax1_cost` double(12,6) DEFAULT '0.000000',
  `reseller2_tax2_cost` double(12,6) DEFAULT '0.000000',
  `reseller2_tax3_cost` double(12,6) DEFAULT '0.000000',
  `reseller2_callcost_total` double(12,6) DEFAULT '0.000000',
  `reseller3_account_id` varchar(30) DEFAULT NULL,
  `reseller3_tariff_id` varchar(30) DEFAULT NULL,
  `reseller3_dp` int(11) DEFAULT NULL,
  `reseller3_ratecard_id` varchar(50) DEFAULT NULL,
  `reseller3_prefix` varchar(50) DEFAULT NULL,
  `reseller3_destination` varchar(50) DEFAULT NULL,
  `reseller3_rate` double(10,6) DEFAULT NULL,
  `reseller3_connection_charge` double(10,6) DEFAULT NULL,
  `reseller3_minimal_time` int(11) DEFAULT NULL,
  `reseller3_resolution_time` int(11) DEFAULT NULL,
  `reseller3_grace_period` int(11) DEFAULT NULL,
  `reseller3_rate_multiplier` double(10,6) DEFAULT NULL,
  `reseller3_rate_addition` double(10,6) DEFAULT NULL,
  `reseller3_duration` int(11) DEFAULT NULL,
  `reseller3_tax1` double(10,6) DEFAULT NULL,
  `reseller3_tax2` double(10,6) DEFAULT NULL,
  `reseller3_tax3` double(10,6) DEFAULT NULL,
  `reseller3_tax_type` varchar(30) DEFAULT NULL,
  `reseller3_callcost` double(10,6) DEFAULT NULL,
  `reseller3_tax1_cost` double(12,6) DEFAULT '0.000000',
  `reseller3_tax2_cost` double(12,6) DEFAULT '0.000000',
  `reseller3_tax3_cost` double(12,6) DEFAULT '0.000000',
  `reseller3_callcost_total` double(12,6) DEFAULT '0.000000',
  `customer_actual_callcost` double(12,6) DEFAULT NULL,
  `reseller1_actual_callcost` double(12,6) DEFAULT NULL,
  `reseller2_actual_callcost` double(12,6) DEFAULT NULL,
  `reseller3_actual_callcost` double(12,0) DEFAULT NULL,
  `billsec` int(11) DEFAULT NULL,
  `start_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `answer_time` datetime DEFAULT NULL,
  `end_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `pdd` int(11) DEFAULT NULL,
  `fscause` varchar(50) DEFAULT NULL,
  `Q850CODE` int(11) DEFAULT NULL,
  `SIPCODE` int(11) DEFAULT NULL,
  `caller_callid` varchar(150) DEFAULT NULL,
  `callee_callid` varchar(150) DEFAULT NULL,
  `common_uuid` varchar(150) DEFAULT NULL,
  `hangupby` varchar(20) DEFAULT NULL,
  `customer_balance` varchar(30) DEFAULT NULL,
  `reseller1_balance` varchar(30) DEFAULT NULL,
  `reseller2_balance` varchar(30) DEFAULT NULL,
  `reseller3_balance` varchar(30) DEFAULT NULL,
  `carrier_callcost_total_usercurrency` double(12,6) DEFAULT '0.000000',
  `carrier_ratio` double(12,6) DEFAULT '1.000000',
  `profit_usercurrency` double(12,6) DEFAULT '0.000000',
  `customer_company_name` varchar(150) DEFAULT NULL,
  `customer_incodecs` varchar(300) DEFAULT NULL,
  `carrier_outcodecs` varchar(30) DEFAULT NULL,
  `call_codecs` varchar(30) DEFAULT NULL,
  `data1` varchar(30) DEFAULT NULL,
  `data2` varchar(30) DEFAULT NULL,
  `cdr_type` varchar(5) DEFAULT 'OUT',
  PRIMARY KEY (`id`,`end_time`),
  KEY `customer_account_id` (`customer_account_id`),
  KEY `end_time` (`end_time`),
  KEY `reseller3_account_id` (`reseller3_account_id`),
  KEY `reseller1_account_id` (`reseller1_account_id`),
  KEY `reseller2_account_id` (`reseller2_account_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- ----------------------------
-- Records of 201908_ratedcdr
-- ----------------------------

-- ----------------------------
-- Table structure for `quick_notes`
-- ----------------------------
DROP TABLE IF EXISTS `quick_notes`;
CREATE TABLE `quick_notes` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `note` text NOT NULL,
  `account_id` varchar(30) NOT NULL,
  `account_name` varchar(100) NOT NULL,
  `dt_created` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` varchar(30) DEFAULT NULL,
  `created_by_name` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=156 DEFAULT CHARSET=latin1;

-- ----------------------------
-- Table structure for `ticket_assigned_to`
-- ----------------------------
DROP TABLE IF EXISTS `ticket_assigned_to`;
CREATE TABLE `ticket_assigned_to` (
  `assigned_to_id` int(11) NOT NULL AUTO_INCREMENT,
  `assigned_to_name` varchar(50) NOT NULL,
  PRIMARY KEY (`assigned_to_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- ----------------------------
-- Records of ticket_assigned_to
-- ----------------------------

-- ----------------------------
-- Table structure for `ticket_attachments`
-- ----------------------------
DROP TABLE IF EXISTS `ticket_attachments`;
CREATE TABLE `ticket_attachments` (
  `attachment_id` int(11) NOT NULL AUTO_INCREMENT,
  `ticket_id` int(11) NOT NULL,
  `file_name` varchar(100) NOT NULL,
  `file_name_display` varchar(100) NOT NULL,
  PRIMARY KEY (`attachment_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- ----------------------------
-- Records of ticket_attachments
-- ----------------------------

-- ----------------------------
-- Table structure for `ticket_categories`
-- ----------------------------
DROP TABLE IF EXISTS `ticket_categories`;
CREATE TABLE `ticket_categories` (
  `category_id` int(11) NOT NULL AUTO_INCREMENT,
  `category_parent_id` int(11) NOT NULL,
  `category_name` varchar(50) NOT NULL,
  `status` enum('Y','N') NOT NULL,
  PRIMARY KEY (`category_id`)
) ENGINE=InnoDB AUTO_INCREMENT=28 DEFAULT CHARSET=latin1;

-- ----------------------------
-- Records of ticket_categories
-- ----------------------------
INSERT INTO `ticket_categories` VALUES ('1', '0', 'Network & Operations', 'Y');
INSERT INTO `ticket_categories` VALUES ('2', '0', 'Accounts', 'Y');
INSERT INTO `ticket_categories` VALUES ('3', '0', 'Sales', 'Y');
INSERT INTO `ticket_categories` VALUES ('4', '0', 'R&D', 'Y');
INSERT INTO `ticket_categories` VALUES ('5', '0', 'Other', 'Y');
INSERT INTO `ticket_categories` VALUES ('6', '1', 'Calling Problems', 'Y');
INSERT INTO `ticket_categories` VALUES ('7', '1', 'Call Records', 'Y');
INSERT INTO `ticket_categories` VALUES ('8', '2', 'Invoices', 'Y');
INSERT INTO `ticket_categories` VALUES ('9', '2', 'Billing', 'Y');
INSERT INTO `ticket_categories` VALUES ('10', '1', 'Low ASR', 'Y');
INSERT INTO `ticket_categories` VALUES ('11', '1', 'Low ACD', 'Y');
INSERT INTO `ticket_categories` VALUES ('12', '1', 'DID Fault', 'Y');
INSERT INTO `ticket_categories` VALUES ('13', '1', 'Incorrect CLI Display', 'Y');
INSERT INTO `ticket_categories` VALUES ('14', '1', 'Voice Break', 'Y');
INSERT INTO `ticket_categories` VALUES ('15', '1', 'One-way Audio', 'Y');
INSERT INTO `ticket_categories` VALUES ('16', '1', 'Hosted Dialler Configuration', 'Y');
INSERT INTO `ticket_categories` VALUES ('17', '1', 'Hosted Dialler Downtime', 'Y');
INSERT INTO `ticket_categories` VALUES ('18', '1', 'Capacity', 'Y');
INSERT INTO `ticket_categories` VALUES ('19', '1', 'Change Request', 'Y');
INSERT INTO `ticket_categories` VALUES ('20', '1', 'Data Connectivity', 'Y');
INSERT INTO `ticket_categories` VALUES ('21', '1', 'Rating', 'Y');
INSERT INTO `ticket_categories` VALUES ('22', '1', 'Reliability', 'Y');
INSERT INTO `ticket_categories` VALUES ('23', '1', 'Security', 'Y');
INSERT INTO `ticket_categories` VALUES ('24', '2', 'Payment', 'Y');
INSERT INTO `ticket_categories` VALUES ('25', '3', 'New Order Enquiry', 'Y');
INSERT INTO `ticket_categories` VALUES ('26', '4', 'Bug Report', 'Y');
INSERT INTO `ticket_categories` VALUES ('27', '4', 'New Feature Requests', 'Y');

-- ----------------------------
-- Table structure for `tickets`
-- ----------------------------
DROP TABLE IF EXISTS `tickets`;
CREATE TABLE `tickets` (
  `ticket_id` int(11) NOT NULL AUTO_INCREMENT,
  `parent_id` int(11) NOT NULL,
  `ticket_number` varchar(20) NOT NULL,
  `subject` varchar(255) NOT NULL,
  `content` text NOT NULL,
  `account_id` varchar(30) NOT NULL,
  `company_name` varchar(100) NOT NULL,
  `category_id` int(11) DEFAULT NULL,
  `assigned_to_id` int(11) DEFAULT NULL,
  `status` enum('open','closed') NOT NULL DEFAULT 'open',
  `hide_from_customer` enum('Y','N') NOT NULL DEFAULT 'N',
  `created_by` varchar(30) NOT NULL,
  `created_by_name` varchar(30) NOT NULL,
  `create_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ticket_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- ----------------------------
-- Records of tickets
-- ----------------------------
